endlessm/eos-meta

- core-armhf
- core-i386
> Added eos-codecs-manager to the eos-core metapackage

- dev-all
> Add Glade as dependency of eos-dev

- core-armhf
- core-i386
> Add gstreamer1.0-libav to the list of core packages

- acknowledgements/kickstarter-backers.txt
This is the list of all backers who pledged at least $5
(and did not opt out of the acknowledgement).
[endlessm/eos-shell#5069]
> Kickstarter "YOUR NAME IN OUR CODE" reward

- debian/control
- debian/eos-acknowledgements.install
Install into /usr/share/EndlessOS/acknowledgements.
[endlessm/eos-shell#5069-debian]
> Create eos-acknowledgements package

- core-armhf
- core-i386
> Add eos-acknowledgements to core image

- core-armhf
- core-i386
> Add vinagre to core packages

- core-armhf
- core-i386
> Add ttf-ancient-fonts package to core OS

- eos-core-depends
> Add unrar to core depends

- eos-core-depends
> Add vino to eos-core dependencies

- eos-core-depends
> Add speedwagon to core package set

- eos-core-depends
> Add UEFI grub to image

- eos-tech-support/eos-check-disk
- eos-tech-support/eos-convert-system
- eos-tech-support/eos-dev-fix
- eos-tech-support/eos-list-users
- eos-tech-support/eos-reset-password
- eos-tech-support/eos-usb-image
Make the eos-tech-support scripts exit on errors so they don't continue and do dangerous things.
[endlessm/eos-shell#5189]
> Exit on errors

- eos-core-depends
> Rename eos-factory-test to eos-factory-tools

- eos-core-depends
> Add simple-scan

- eos-tech-support/eos-convert-system-qa
> convert-system-qa: add an option to keep the journal persistent

- eos-tech-support/eos-convert-system
> convert-system: Hardlink /endless as well so it doesn't disappear

- eos-core-depends
> Renamed eos-pepflashplugin-updater to eos-chrome-plugin-updater

- eos-tech-support/eos-convert-system
Most developers want something like this.
> eos-convert-system: Make the journal persistent

- eos-core-depends
> Install eos-chrome-plugin-updater in every platform

- eos-tech-support/eos-convert-system
- eos-tech-support/eos-convert-system-qa
Enable systemd coredumps processing and storage on eos-convert-system{,-qa}
https://phabricator.endlessm.com/T6048
> T6048: Enable systemd coredumps processing and storage on eos-convert-system{,-qa}

- eos-tech-support/eos-convert-system-qa
Make sure the updater is not running and will not be spawned while the configuration is being adjusted.
https://phabricator.endlessm.com/T10881
> convert-system-qa: Stop updater before changing config

- eos-core-depends
https://phabricator.endlessm.com/T11140
> Add radeon and amdgpu X drivers

- eos-core-depends
https://phabricator.endlessm.com/T10823
> Jessie updates

- debian/.gitignore
- debian/eos-tech-support.postinst
- eos-tech-support/eos-convert-passwd
- eos-tech-support/eos-convert-system
https://phabricator.endlessm.com/T11410
> Merge passwd files back to /etc when converting

- debian/.gitignore
- debian/control
- eos-core-amd64-depends
- eos-core-depends
- eos-installer-meta-amd64-depends
- os-depends
https://phabricator.endlessm.com/T11417
> amd64 metapackages

- base-depends
https://phabricator.endlessm.com/T10823
> Switch to iproute2

- os-depends
https://phabricator.endlessm.com/T11594
> os-depends: add dconf-cli

- eos-installer-meta-depends
https://phabricator.endlessm.com/T11658
> Installer: use eos-installer instead of gnome-initial-setup

- os-depends
https://phabricator.endlessm.com/T11755
> os-depends: add exfat-utils

- eos-tech-support-depends
Useful for viewing or setting wireless network interface parameters.
https://phabricator.endlessm.com/T11997
> Install iw

- os-depends
https://phabricator.endlessm.com/T12093
> os-depends: Add shim-efi-image

- eos-core-depends
https://phabricator.endlessm.com/T12069
> Add xdg-desktop-portal and xdg-desktop-portal-gtk to the core deps

- eos-core-depends
https://phabricator.endlessm.com/T12269
> Add gnome-font-viewer

- eos-core-depends
https://phabricator.endlessm.com/T12231
> Add xapian-bridge back to eos-core

- base-depends
- eos-platform-runtime-depends
https://phabricator.endlessm.com/T12231
> Fix GTK2/GTK3 modules for libcanberra/caribou

- eos-platform-runtime-depends
This includes:
* introspection packages for some libs in the runtime
* libjson-glib with its introspection package
* libclutter-gst with its introspection package
https://phabricator.endlessm.com/T12303
> Add some packages for Pitivi flatpak

- eos-sdk-runtime-depends
This is needed to build subscriptions apps.
https://phabricator.endlessm.com/T11523
> sdk: add eos-knowledge-0-dev

- eos-core-depends
https://phabricator.endlessm.com/T12367
> core: don't depend on ibus-tegaki

- eos-platform-runtime-depends
This package provides eminem and kermit which
are essential diagnostic tools for knowledge
apps.
https://phabricator.endlessm.com/T12368
> runtime: add eos-knowledge-0-bin

- eos-platform-runtime-depends
https://phabricator.endlessm.com/T12605
> eos-platform-runtime-depends: Add libxss1

- eos-core-depends
https://phabricator.endlessm.com/T12342
> add eos-phone-home to OS to send activate message on first boot

- eos-tech-support/eos-diagnostics
https://phabricator.endlessm.com/T12710
> eos-diagnostics: add graphics renderer information

- eos-tech-support-depends
- eos-tech-support/eos-download-image
- eos-tech-support/eos-write-installer
https://phabricator.endlessm.com/T12550
> eos-write-installer fixups

- eos-platform-runtime-depends
These are needed for the Chinese curriculum apps.
First merge this OBS request: https://obs-master.endlessm-sf.com/request/show/10339
https://phabricator.endlessm.com/T12582
> Add fonts-noto-cjk to runtime

- eos-tech-support/eos-launch-all
https://phabricator.endlessm.com/T12824
> eos-launch-all: add flatpak support

- base-depends
https://phabricator.endlessm.com/T12845
> base-depends: Added gvfs backends as a core dependency

- os-depends
We have created a separate package to provide the binaries signed by
Microsoft.
https://phabricator.endlessm.com/T12941
> os: Install the Microsoft-signed version of shim

- os-depends
Guest additions for GNOME Boxes
https://phabricator.endlessm.com/T13100
> os-depends: spice-vdagent

- eos-tech-support-depends
- eos-tech-support/eos-download-image
- eos-tech-support/eos-write-image
- eos-tech-support/eos-write-installer
- eos-tech-support/eos-write-live-image
https://phabricator.endlessm.com/T12549
https://phabricator.endlessm.com/T12753
> Add eos-write-live

- eos-tech-support/eos-download-image
https://phabricator.endlessm.com/T13412
> Three oh fixes

- eos-tech-support/eos-write-image
- eos-tech-support/eos-write-installer
- eos-tech-support/eos-write-live-image
https://phabricator.endlessm.com/T13374
> eos-write-*: Remove fallback.efi from removable devices

- eos-tech-support/eos-diagnostics
And call it the more generic "Chromium plugins info", since the
directory includes both Flash and Widevine.
https://phabricator.endlessm.com/T13464
> eos-diagnostics: fix Flash version information

- eos-tech-support/eos-write-image
https://phabricator.endlessm.com/T13374
> eos-write-image: Move grubx64.efi on removable devices

- eos-tech-support/eos-download-image
I forgot about this script when I changed the JSON format!
https://phabricator.endlessm.com/T13224
> eos-download-image: fix fetching boot.zip[.asc]

- eos-sdk-runtime-depends
We need some of these in order to be able to build a custom webkit for
com.endlessm.programming.
> Dependencies for com.endlessm.Sdk

- eos-tech-support/eos-write-image
- eos-tech-support/eos-write-installer
- eos-tech-support/eos-write-live-image
https://phabricator.endlessm.com/T11518
> T11518 add .xz support to eos-write-* tools

- eos-sdk-runtime-depends
> Add uuid-dev to the SDK dependencies

- eos-tech-support/eos-write-live-image
https://phabricator.endlessm.com/T13701
> write-live-image: reduce output; improve error reporting

- eos-sdk-runtime-depends
> com.endlessm.Sdk: added wrong webkit

- eos-platform-runtime-depends
- eos-sdk-runtime-depends
https://phabricator.endlessm.com/T13476
> Update OpenJDK packages to openjdk-8-*

- eos-sdk-runtime-depends
Needed for building eos-programming.
> Add python-polib to com.endlessm.Sdk

- eos-platform-runtime-depends
https://phabricator.endlessm.com/T13448
> runtime: include extra fontconfig configuration for flatpak

- eos-tech-support/eos-diagnostics
https://phabricator.endlessm.com/T13464
> eos-diagnostics: Check the right VERSION files for chromium plugins

- debian/rules
https://phabricator.endlessm.com/T13322
https://phabricator.endlessm.com/T13865
> Symlinks allowing Flatpak app bundles to provide a 32-bit userland

- debian/control
- eos-core-s905x-depends
- eos-installer-meta-s905x-depends
- s905x-depends
https://phabricator.endlessm.com/T14004
> Add s905x metapackages

- eos-core-depends
https://phabricator.endlessm.com/T14100
> Add eos-google-chrome-helper to the core OS for amd64

- eos-sdk-runtime-depends
https://phabricator.endlessm.com/T13418
> eos-sdk-runtime-depends: add knowledge content dev package

- os-depends
https://phabricator.endlessm.com/T14023
> Switch to signed kernel/bootloader packages

- debian/defaults.list
https://phabricator.endlessm.com/T14796
> defaults.list: set Processing as default for its mimetype

- eos-tech-support/eos-write-live-image
https://phabricator.endlessm.com/T13558
> ISO: Switch to a UEFI fully compliant MBR-only ISO image

- eos-tech-support/eos-convert-system-qa
https://phabricator.endlessm.com/T14857
> if statement needs a then after it

- eos-tech-support/eos-write-live-image
https://phabricator.endlessm.com/T13560
> ISO: Ship a squashfs image

- eos-tech-support/eos-write-live-image
https://phabricator.endlessm.com/T15147
> write-live-image: work around eos-installer bug for FNDE

- debian/control
- eos-tech-support-depends
- eos-tech-support-iso-depends
- eos-tech-support/eos-write-image
- eos-tech-support/eos-write-live-image
https://phabricator.endlessm.com/T13559
> Fixes needed to generate ISOs from image builder

- eos-tech-support/eos-diagnostics
This was accidentally lost during a previous reorganization.
https://phabricator.endlessm.com/T15496
> eos-diagnostics: report installed flatpak runtimes and apps

- eos-tech-support/eos-write-live-image
https://phabricator.endlessm.com/T15588
> ISO: Do not use fragments for the squashfs image

- eos-tech-support/eos-diagnostics
Two commits to add `systemd-coredump` support to `eos-diagnostics`.
https://phabricator.endlessm.com/T15177
> T15177 coredumps

- eos-tech-support/eos-write-live-image
https://phabricator.endlessm.com/T15588
> Revert "ISO: Do not use fragments for the squashfs image"

- eos-core-depends
This package contains the handler script for webapp:// URIs.
https://phabricator.endlessm.com/T15917
> eos-core: Added eos-browser-tools

- eos-tech-support-depends
- eos-tech-support/eos-download-image
Deal with CloudFront refusing to download files that are larger than 20 GB like the FNDE Escola images now are.
https://phabricator.endlessm.com/T16099
> eos-download-image: Handle files above 20 GB

- eos-tech-support/eos-download-image
- eos-tech-support/eos-write-image
- eos-tech-support/eos-write-live-image
I am *more* than happy to defer the final commit to a separate PR. It looks like it rewrites the file, but it's mostly indenting 4 spaces to the right and replacing repeated arguments with `self.foo`. Much easier to read in `git show --ignore-space-change`.
https://phabricator.endlessm.com/T16171
> Update eos-tech-support tools to handle ISOs

- eos-tech-support/eos-write-image
- eos-tech-support/eos-write-installer
- eos-tech-support/eos-write-live-image
https://phabricator.endlessm.com/T15598
> eos-write-{image,live-image,installer}: yet more partprobe stuff

- debian/control
- eos-dev-kernel-depends
https://phabricator.endlessm.com/T16588
> Add eos-dev-kernel metapackage

- debian/control
- eos-dev-kernel-amd64-depends
- eos-dev-kernel-armhf-depends
https://phabricator.endlessm.com/T16588
> Add eos-dev-kernel-{amd64,armhf} metapackages

- eos-core-depends
https://phabricator.endlessm.com/T16741
> DiscoveryFeed: add eos-discovery-feed to the images

- eos-core-depends
https://phabricator.endlessm.com/T17912
> Add OpenVPN plugin for network-manager

- eos-tech-support/eos-stage-flatpak
https://phabricator.endlessm.com/T18127
> eos-stage-flatpak: update new eos-sdk flatapk repo, too

- eos-tech-support/eos-diagnostics
This matches f934324 which made the same change for eos-dev-fix.
https://phabricator.endlessm.com/T18503
> eos-diagnostics: update for /var/lib/dpkg presence

- base-depends
- os-depends
This includes some closed source code, but with an acceptable
license for redistribution.
https://phabricator.endlessm.com/T19150
> Add proprietary nvidia drivers

- eos-core-depends
- eos-language-pack-ar-depends
- eos-language-pack-bn-depends
- eos-language-pack-de-depends
- eos-language-pack-en-depends
- eos-language-pack-es-depends
- eos-language-pack-fr-depends
- eos-language-pack-id-depends
- eos-language-pack-pt-br-depends
- eos-language-pack-pt-depends
- eos-language-pack-ro-depends
- eos-language-pack-th-depends
- eos-language-pack-vi-depends
- eos-language-pack-zh-cn-depends
- eos-language-pack-zh-tw-depends
https://phabricator.endlessm.com/T19192
> T19192: re-add LibreOffice to core OS

- eos-core-depends
Proposal to include this on the core system.
https://phabricator.endlessm.com/T18496
> core: Add python3-flapjack

- eos-tech-support/eos-fix-ostree-repo
Copied out of a comment on https://phabricator.endlessm.com/T18946 so
they don’t get lost.
> eos-fix-ostree-repo: Add some testing instructions

- eos-platform-runtime-depends
Still needed for resume and finance apps.
https://phabricator.endlessm.com/T18693
> eosplatform: Add WebKit1 dependency

- eos-tech-support/eos-download-image
https://phabricator.endlessm.com/T19919
> eos-download-image: add timeouts to HTTP requests

- os-depends
https://phabricator.endlessm.com/T19800
> os-depends: Add microcode packages

- base-depends
https://phabricator.endlessm.com/T19704
> Install the correct GL packages for GLVND

- eos-tech-support/eos-stage-flatpak
https://phabricator.endlessm.com/T18103
> eos-stage-flatpak: Passwordless eos-sdk staging/dev

- eos-tech-support/eos-convert-system
https://phabricator.endlessm.com/T19614
> eos-convert-system: Force update-grub

- os-depends
https://phabricator.endlessm.com/T14870
> os-depends: Rename grub-efi-amd64-image to grub-efi-ia32-image

- eos-core-depends
https://phabricator.endlessm.com/T20707
> eos-core: Add eos-companion-app-os-integration

- eos-tech-support/eos-stage-flatpak
Iterate through all Endless app repos so that they don't have to
be individually hard-coded.
https://phabricator.endlessm.com/T20847
> eos-stage-flatpak: handle any Endless app repo

- eos-tech-support/eos-write-image
- eos-tech-support/eos-write-installer
https://phabricator.endlessm.com/T11946
> Improve error messages from eos-write-{installer,image}

- ec100-depends
- odroidu2-depends
- os-depends
- s905x-depends
https://phabricator.endlessm.com/T21539
> Make xserver-xorg-video-armsoc platform dependent

- ec100-depends
- eos-core-ec100-depends
- eos-core-odroidu2-depends
- eos-core-s905x-depends
- eos-installer-meta-ec100-depends
- eos-installer-meta-s905x-depends
- odroidu2-depends
- os-ec100-depends
- os-odroidu2-depends
- os-s905x-depends
- s905x-depends
https://phabricator.endlessm.com/T21342
> Factor out a os-<platform>-depends file

- eos-core-amd64-depends
- eos-core-i386-depends
- eos-core-rk3288-depends
- eos-core-sqwerty-depends
- eos-installer-meta-amd64-depends
- eos-installer-meta-i386-depends
- eos-installer-meta-nexthw-depends
- os-amd64-depends
- os-depends
- os-ec100-depends
- os-i386-depends
- os-nexthw-depends
- os-odroidu2-depends
- os-rk3288-depends
- os-s905x-depends
- os-sqwerty-depends
https://phabricator.endlessm.com/T21441
> Introduce platfrom specific xserver-xorg-* dependency

- os-rk3288-depends
Signed-off-by: Carlo Caione <carlo@endlessm.com>
> rk3288: Add libmali to rk3288 image

- eos-core-depends
https://phabricator.endlessm.com/T22015
> Fix gdk-pixbuf2 package name

- eos-tech-support/eos-diagnostics
https://phabricator.endlessm.com/T22043
> eos-diagnostics: add a help command to show usage

- rk3288-depends
https://phabricator.endlessm.com/T22733
> rk3288: Add flashrom package

- rk3288-depends
https://phabricator.endlessm.com/T23130
> rk3288: Add ectool package

- eos-tech-support/eos-diagnostics
Noticed by Jack75 on the Endless forum.
https://community.endlessos.com/t/phantom-updates-in-app-center/7104/10
https://phabricator.endlessm.com/T23268
> eos-diagnostics: fix "too many arguments" warning

- eos-tech-support/eos-hack-reset-clubhouse
https://phabricator.endlessm.com/T24908
> eos-hack-reset-clubhouse: Reset cursor customizations

- os-depends
https://phabricator.endlessm.com/T24742
> os-depends: add fscrypt and libpam-fscrypt to the ostree

- eos-core-depends
https://phabricator.endlessm.com/T26404
> core-depends: add buildah

- eos-core-depends
https://phabricator.endlessm.com/T26430
> core-depends: add toolbox

- debian/control
- eos-toolbox-dev-depends
https://phabricator.endlessm.com/T26442
> Add metapackage for eos-toolbox-dev

- os-depends
https://phabricator.endlessm.com/T27241
> os: Install Checkbox and the initial hw evaluation test plan

- debian/control
- eos-initramfs-efi-depends
This will include all the packages needed for the kernel build to
build us a dracut initramfs+kernel efi blob
> Add eos-initramfs-efi

- eos-core-depends
https://phabricator.endlessm.com/T27461
> Include thermald in the core OS

- eos-tech-support/eos-add-to-desktop
Pulled a couple fixes from #601
> Tweak eos-add-to-desktop

- os-depends
https://phabricator.endlessm.com/T28684
> os: Add VMWare Guest Extensions (open-vm-tools)

- eos-core-depends
https://phabricator.endlessm.com/T30294
> core: Drop eos-discovery-feed

- eos-tech-support/eos-write-live-image
This option allows to copy extra files to the USB exFAT partition.
https://phabricator.endlessm.com/T30586
> eos-write-live-image: add --copy-path option

- eos-core-depends
It will replace the panel modifications we used to carry on GNOME Shell itself.
https://phabricator.endlessm.com/T30445
> core: Add eos-panel-extension

- eos-core-depends
https://phabricator.endlessm.com/T30650
> Add force-quit-dialog-extension to core packages

- eos-core-depends
https://phabricator.endlessm.com/T30237
> core: Add eos-tour-extension

- eos-core-depends
https://phabricator.endlessm.com/T25765
> core: Drop Totem in favour of flathub version

- eos-core-depends
https://phabricator.endlessm.com/T30886
> eos-core-depends: Remove python3-flapjack

- eos-core-depends
We finally integrate Kolibri system wide.
https://phabricator.endlessm.com/T31182
> core: add eos-kolibri

- os-depends
Discussed at https://community.endlessos.com/t/packages-missing-in-development-version/16280
> Added rsync as a os dependency

- eos-core-depends
As suggested in https://community.endlessos.com/t/discussion-plugins-for-more-vpn-providers/16384
> Added support for L2TP and Cisco AnyConnect VPNs

- os-depends
drop the others.
Backstory: https://community.endlessos.com/t/xterm-shows-in-3-10/16322/11
> Add important priority packages that we actually want so we can

- eos-core-depends
Drop cups-browsed since this functionality is now better provided by
cups
https://phabricator.endlessm.com/T31857
> eos-core: Remove cups-browsed

- eos-core-depends
This reverts commit 284fd34f147d152eb3b11341d4ae8be5b251fe67.
https://phabricator.endlessm.com/T31963
> Revert "core: Add libfsapfs-utils package"

- os-depends
This is tiny, but very useful for diagnostics.
> Add mtr-tiny

- eos-core-depends
- os-depends
Add a few packages that are recommended in bullseye that we might want. This is based on the package-recommends output and obviously is somewhat subjective.
https://phabricator.endlessm.com/T32328
> Fixes for bullseye recommendations

- eos-tech-support/eos-diagnostics
https://phabricator.endlessm.com/T32495
> Update eos-diagnostics: -split disk, +split repo

- debian/control
- ec100-depends
- eos-core-ec100-depends
- eos-core-s905x-depends
- eos-installer-meta-ec100-depends
- eos-installer-meta-s905x-depends
- s905x-depends
https://phabricator.endlessm.com/T30303
> Remove 32-bit ARM metapackages

- eos-core-depends
- eos-tech-support/eos-user-stress-test
Thread: https://community.endlessos.com/t/apps-that-have-flatpaks/17442/4
https://phabricator.endlessm.com/T31431
> Move shotwell to flatpaked

- eos-core-depends
https://phabricator.endlessm.com/T32879
> core: Move gedit to Flatpak

- eos-core-depends
https://phabricator.endlessm.com/T32906
> core: Move gnome-calculator to Flatpak

- eos-core-depends
https://phabricator.endlessm.com/T32908
> core: Move gnome-logs to Flatpak

- eos-core-depends
https://phabricator.endlessm.com/T32912
> core: Move gnome-font-viewer to Flatpak

- eos-core-depends
These were flagged by the recommends checker. Rationale for each in each commit message.
https://phabricator.endlessm.com/T32975
> Readd gnome-menus; add libpipewire-0.3-common

- eos-core-depends
https://phabricator.endlessm.com/T32983
> core: Move gnome-contacts to Flatpak

- eos-core-depends
https://phabricator.endlessm.com/T33040
> core: Move file-roller to Flatpak

- eos-core-depends
https://phabricator.endlessm.com/T32829
> eos-core: Install gnome-tour

- eos-tech-support/eos-diagnostics
https://phabricator.endlessm.com/T33942
> eos-diagnostics: Add info from upower

- os-depends
https://phabricator.endlessm.com/T32527
> os-depends: Install low-memory-monitor
