endlessm/eos-meta

- core-armhf
- core-i386
This was probably never used in the first place, but certainly now
all packages come from Endless repos and not from Collabora. Neither our
users nor developers have any use for singularity's keyring.
[endlessm/eos-shell#5053]
> Remove singularity-archive-keyring from core

- core-armhf
- core-i386
We're once again depending on libav to provide codec support, but
currently this is only implicitly pulled in via gstreamer1.0-libav. This
doesn't use all the libav libraries, but some bundles do require. For
example, mplayer requires libswscale. Explicitly add all libav libraries
from the current source package.
[endlessm/eos-shell#5158]
> Bring back libav packages

- eos-tech-support/eos-convert-system
- eos-tech-support/eos-convert-system-qa
- eos-tech-support/eos-dev-fix
The updater programs have changed around a bit with the ostree upgrade.
The actual updates daemon has been changed from ostree-daemon to
eos-updater as ostree-daemon has been determined to be Endless specific.
The systemd service driving the updater has been changed from
eos-updater to eos-autoupdater.
[endlessm/eos-shell#5087]
> tech-support: Adjust to new updater names

- core-armhf
- core-i386
Provide the OSTree introspection typelib so that the OSTree API can be
accessed in any way. Sort the list while here.
[endlessm/eos-shell#5195]
> Add gir1.2-ostree-1.0 to core

- eos-tech-support/eos-dev-fix
- eos-tech-support/eos-reset-password
- eos-tech-support/eos-usb-image
Newer ostree has removed the current deployment symlink and instead
offers the --print-current-dir option from ostree admin. This requires
that the boot directory is properly mounted to find the current
deployment.
Fix up a couple things on eos-dev-fix while here:
* Use awk to scrape mountinfo in a simpler way
* Check that we're booted in an ostree system
* Check for an upgrade prior to stopping the automatic updater.
[endlessm/eos-shell#5189]
> tech-support: Use admin --print-current-dir instead of current symlink

- eos-core-depends
This is needed in order for gnome-disks to be able to format
and manage partitions on an external drive.
[endlessm/eos-shell#5354]
> Add parted to image

- eos-core-depends
Nothing that we ship on an image currently requires it, but some bundles
from EOS 2.3 need it, so we are keeping it for compatibility reasons.
[endlessm/eos-sdk#3387]
> Keep gir1.2-webkit2-3.0 in core

- eos-tech-support/eos-convert-system-qa
Hack around `ostree admin set-origin` being broken. This
can be reverted when the upstream bug at
https://bugzilla.gnome.org/show_bug.cgi?id=753373 is fixed.
[endlessm/eos-shell#5433]
> Fix `eos-convert-system-qa` by working around ostree bugs

- debian/eos-core.install
It's not needed any longer.
[endlessm/eos-shell#4389]
> Don't install anything in /etc/skel

- eos-core-depends
This allows generation of backtraces on production systems.
[endlessm/eos-shell#6010]
> Install gdb by default

- eos-core-depends
This does not integrate with wine, and is built/valid for all.
[endlessm/eos-shell#6116]
> Install eos-gates for all architectures

- eos-tech-support-depends
Useful to allow field support to use Endless as the receiving computer
for troubleshooting via the UART serial console.
[endlessm/eos-shell#6174]
> Tech support: install screen utility

- eos-core-depends
- eos-platform-depends
Remove Empathy as per #5683. Remove Telepathy as well -- it will get
pulled in if the user installs Empathy manually. Also, remove the
Telepathy Folks plugin. It seemed undesirable to keep Telepathy around
by default just for this plugin. I can't think of why it would be
useful, except for GNOME Contacts, which is not installed.
[endlessm/eos-shell#5683]
> Do not install Empathy or Telepathy

- eos-core-depends
This script stores a timestamp on shutdown, and restores that time
on startup (unless the current time is newer, for example due to
a working battery-backed hardware clock).
This is useful for products that don't have a battery-backed
hardware clock, so that time stamps are monotonically increasing,
and NTP incremental updates are faster.
[endlessm/eos-shell#1431]
> Install fake-hwclock

- eos-tech-support/eos-write-image
> eos-write-image: Format device with 'blkdiscard'

- eos-core-depends
This change depends on [OBS request 2641](https://obs-master.endlessm-sf.com/request/show/2641), please merge that one first.
We have a new kernel flavour generic-64 which provides a 64-bit kernel
as i386 packages, so they can be installed in a i386 system. Switch to
them so we can move the kernel to 64-bit while keeping a 32-bit
userspace.
[endlessm/eos-shell#6302]
> [endlessm/eos-shell#6302] Switch images to a 64-bit kernel

- debian/control
- eos-core-depends
- eos-language-pack-id-depends
Note that there is LibreOffice help pack for Indonesian.
Also, our current KDE version does not have an Indonesian pack,
and though there is now a kde-l10n-id available in debian sid,
it does not appear to cover any of our KDE applications anyhow.
[endlessm/eos-shell#6283]
> Add Indonesian (id) language pack

- eos-tech-support/eos-diagnostics
Output of systemd-analyze.
[endlessm/eos-shell#6346]
> eos-diagnostics: add boot timing

- eos-core-depends
This package is a required dependency of turtleblocks.
Previously, we inherently installed as a dependency of hplip,
but with an upgrade to hplip that is no longer the case.
[endlessm/eos-shell#6356]
> Add explicit dependency on python-dbus

- eos-core-depends
This package is a required dependency of megaglest.
Previously, this was inherently installed due to a core dependency,
and that is apparently no longer the case.
[endlessm/eos-shell#6368]
> Add explicit dependency on libglu1-mesa

- eos-core-depends
After upgrades to gedit and totem, these are no longer pulled into the
core, but they're needed by pitivi, gnome-sudoku and labyrinth.
[endlessm/eos-shell#6415]
> Add python-gi-cairo and python-xdg to core for apps

- eos-tech-support/eos-write-image
> eos-write-image: Do not stop when blkdiscard fails

- eos-platform-runtime-depends
It is required by several packages and was already part of eos-core,
so it makes sense this becomes part of the runtime.
In the mid-term, this should not be here but in a runtime extension,
so it would be possible to load different GL libs depending on the
hardware platform.
> Add dependency on libglu1-mesa to xdg-app runtime

- eos-core-depends
As we have a mixed 64-bit kernel and 32-bit userland in the 2.6 series, a bunch of miscellaneous stuff (eg Spice's QXL or NVidia proprietary X drivers) gets unhappy if the userland and kernel aren't both the same, which is a pain for some developers. While we're building both kernels, you can fix this by manually installing the 32-bit kernel package if you're on a converted system. This patch allows you to remove the 64-bit kernel without breaking the eos-core dependencies, so you can makes Grub default to the 32-bit one without hacking around with the grub config or removing the eos-core metapackage and falling behind master.
> allow 32-bit kernel instead of 64-bit kernel

- eos-core-depends
Note: This SHOULD BE UNDONE as soon as we move to 64-bit for Intel products.
https://phabricator.endlessm.com/T10669
> Add eos-chrome-plugins-updater-s3 to the list of core dependencies

- eos-core-depends
- eos-platform-runtime-depends
There are many xdg-app application bundles using the Endless runtime that will depend on the missing libcanberra-gtk3-0, so it seems a good idea to add it directly to the runtime. Also adding it explicitly on eos-core although it was being already pulled into by some other dep.
[endlessm/eos-shell#6291]
> Add libcanberra-gtk3-0 dependency to eos-core and eos-platform-runtime

- eos-core-depends
- eos-platform-runtime-depends
In order to run some of the sandboxed xdg-app bundles that are being produced, there are still some missing dependencies in the runtime. Also making them explicit on eos-core although they were already being already pulled into by some other dep.
> Add missing dependencies for xdg-app bundles

- eos-core-depends
Previously, we relied an eos-file-manager recommending brasero,
but the latest version of nautilus merely suggests brasero,
so it was not getting installed.
https://phabricator.endlessm.com/T11139
> Explicitly depend on brasero

- eos-core-depends
- eos-platform-runtime-depends
In moving back to the Debian version of libgc, they've kept the library
at libgc1c2 rather than changing it to libgc1c3 like Ubuntu did. Update
the core/platform dependency accordingly.
https://phabricator.endlessm.com/10823
> Change libgc depdendency to libgc1c2

- eos-tech-support/eos-launch-all
We no longer prefix the desktop names with "eos-app-",
so instead we can now check for the "X-Endless-Merged" field
inside the dekstop file to isolate which core apps
we expose to the user via desktop icons.
https://phabricator.endlessm.com/T10982
> eos-launch-all: fix launching of core apps

- eos-core-depends
https://phabricator.endlessm.com/T11319
> Add imagescan to the core dependencies, needed for some Epson scanners

- eos-core-depends
- eos-platform-runtime-depends
glew got updated. Some app rebuilds will be needed to link to the new
version of libglew.
https://phabricator.endlessm.com/T10823
> Depend on libglew1.10

- eos-core-depends
- eos-platform-runtime-depends
suitesparse is being updated, so depend on the new libumfpack5.6.2. Some
apps will need to be rebuilt to link to the new version.
https://phabricator.endlessm.com/T10823
> Update libumfpack dependency

- eos-core-depends
On our newer systemd (229) systemd-coredump and coredumpctl are part of
a separate package.
https://phabricator.endlessm.com/T6363
> Add systemd-coredump as a dependency of eos-core

- eos-tech-support/eos-convert-system
On converted systems the root partition is not mounted to /sysroot, so
/sysroot/boot should not be mounted over /boot.
https://phabricator.endlessm.com/T11374
> T11374: convert-system: Disable /boot bind mount

- eos-core-depends
This package is no longer available from webkigtk > 2.4.9, so let's
remove it from here. Note that this will break the Virtual School
bundle from EOS 2.3, but considering that would be a pretty old
bundle at the time the user gets the 2.7 release, and that we will
have to migrate a lot of stuff anyway because of the 32bit > 64bit
switch, this actually seems like a good moment to get rid of it.
For more information on why this dependency has been introduced,
please check this out: https://phabricator.endlessm.com/T9824
https://phabricator.endlessm.com/T11388
> Remove explicitly dependency on gir1.2-webkit2-3.0

- eos-core-depends
We don't even build the packages yet for these, so they're just causing
the ostree build to fail.
https://phabricator.endlessm.com/T11417
> core: Disable plugin updaters on amd64

- eos-tech-support/eos-convert-system
This reverts commit c11becad03162206f84b62a394cec12658e5df3c.
Don't disable the boot.mount unit on eos-convert-system, since now its
execution is controlled by conditionals on the unit file.
https://phabricator.endlessm.com/T11374
> T11374: Revert "convert-system: Disable /boot bind mount"

- os-depends
I am assuming that *os-dependencies* is the right place to add *gnome-software*. Otherwise just let me know.
> Add gnome-software to OS dependencies

- eos-core-depends
xdg-app is a main component for the 2.7 release so we should have it
added by default in the images.
> Add xdg-app to base depends

- os-depends
Make the core os packages pull the libinput X input driver instead of
synaptics and evdev.
https://phabricator.endlessm.com/T11530
> Switch to libinput

- app-depends
Required by gcompris and probably by other apps.
https://phabricator.endlessm.com/T11355
> Add libpython2.7 to app dependencies

- eos-tech-support/eos-convert-system
/usr needs to be remounted rw before running eos-convert-passwd, so it
can remove /lib/passwd in the end of the process.
https://phabricator.endlessm.com/T11487
> tech-support: Remount /usr rw before eos-convert-passwd

- app-depends
Required by GCompris and probably by other apps.
https://phabricator.endlessm.com/T11355
> Add python-cairo to app-depends

- debian/control
- eos-installer-meta-depends
- eos-installer-meta-ec100-depends
- eos-installer-meta-i386-depends
This will be used for a minimal USB OS/image for flashing Endless images
to disks. The idea is to have a minimal desktop that starts directly
into a flashing tool. This is a cut down eos-core with almost all of the
explicit library dependencies have been removed as it's expected that
they'll be pulled in as necessary by other packages.
The eos-installer-meta name is used to prevent a collision with the
likely eos-installer package that will provide the actual flashing tool.
This is a backport of e086088 without the refactoring to split up the
depends files into common subsets.
https://phabricator.endlessm.com/T11283
> Add eos-installer-meta metapackage

- eos-platform-runtime-depends
These packages are only available in the shared repo because reprepro
doesn't remove them, but we don't have them for amd64. As it is, on
master the apps should be fixed up to depend on the current versions of
these libraries. Eventually the entire app-depends file will be moved
into the platform depends file when we no longer support bundles.
https://phabricator.endlessm.com/T11586
> platform: Drop compat libraries

- eos-tech-support/eos-convert-system
This was lost when systemd-coredump started requiring more parameters
after the last systemd upgrade.
https://phabricator.endlessm.com/T11631
> eos-convert-system: add back rlimit parameter to core pattern

- eos-tech-support/eos-launch-all
Otherwise, we might run into the situation where the regular user can't
properly run some apps afterwards, as all the permissions will be broken.
https://phabricator.endlessm.com/T11630
> Do not allow to run eos-launch-all with superuser privileges

- os-depends
Otherwise, we'll just get a solid blue background.
Note that this is just a single background image that will serve
all languages, without any regional customization like we have
for the full OS.
https://phabricator.endlessm.com/T11712
> Add default background for installer

- eos-installer-meta-depends
This will provide the image signing keys in
/usr/share/keyrings/eos-image-keyring.gpg, and the installer will use it
to verify downloaded images.
https://phabricator.endlessm.com/T11727
> installer: Include eos-image-keyring

- base-depends
- eos-platform-runtime-depends
- os-depends
eos-default-settings only belongs to the OS.
eos-icon-theme belongs to both the OS and the runtime.
eos-extra-fonts only belongs to the runtime.
https://phabricator.endlessm.com/T11779
> Follow split of eos-theme binary packages

- eos-tech-support/eos-add-to-desktop
Adds an application with the specified app ID to the desktop
(where the appid.desktop file already exists).
https://phabricator.endlessm.com/T11824
> eos-add-to-desktop: new script

- eos-tech-support/eos-convert-system
Don't error out if a directory (e.g., the journal) already exists.
https://phabricator.endlessm.com/T11889
> eos-convert-system: add -p to mkdir

- eos-tech-support/eos-convert-system
Now that dracut and linux-meson packages are providing binaries directly
compatible with the bootloader, we can treat ARM kernels as normal:
restore the way that they were installed from packages.
We also set up the same symlinks that linux-meson postinst does, and
make the bootloader use these links, allowing for ARM kernels to be
updated with apt.
https://phabricator.endlessm.com/T1404
> eos-convert-system: restore package layout for ARM kernels too

- eos-tech-support/eos-check-secureboot
- eos-tech-support/eos-convert-system
Secure boot should be disabled before running eos-convert-system,
because the kernel in our package will not be signed
https://phabricator.endlessm.com/T12159
> eos-convert-system: Check if we're running under secure boot

- eos-tech-support/eos-check-secureboot
If the EFI variable file is not found our python code exits with an
error, what is equivalent to reporting secureboot is enabled. Catch the
IOError exception and report we're not under secure boot.
https://phabricator.endlessm.com/T12159
> check-secureboot: Handle absence of the EFI vars

- os-depends
Shim is only built on amd64, and it will only ever work on amd64 as far
as I know. Without this, the i386 builds are broken.
https://phabricator.endlessm.com/T12093
> os: Install shim-efi-image only on amd64

- eos-platform-runtime-depends
These should be part of the runtime.
https://phabricator.endlessm.com/T12240
> app-depends: add python-gi/python3-gi

- eos-sdk-runtime-depends
This is typically needed to build Endless apps.
> Add ruby-sass to the SDK dependencies

- eos-core-depends
Provides cdrdao and toc2cue binaries, which are required by brasero
to record a music CD.
https://phabricator.endlessm.com/T12145
> core: Add cdrdao

- eos-core-depends
Provides the "smb" backend to CUPS for printers shared from Windows.
https://phabricator.endlessm.com/T12148
> core: Add smbclient

- eos-tech-support/eos-convert-system
If the /lib64 -> usr/lib64 symlink is not copied here, systemd will
recreate it as usr/lib/x86_64-linux-gnu. This subsequently blows up when
glibc is upgraded because it makes 2 paths in the package the same real
path.
https://phabricator.endlessm.com/T11645
> eos-convert-system: Handle /lib64

- eos-core-depends
This package is needed for the KA Lite flatpak to work, as it provides
the OS-related bits like the kalite user and integration with systemd.
https://phabricator.endlessm.com/T4489
> core: Add eos-kalite-system-helper

- eos-tech-support/eos-diagnostics
This should help common situations where the audio hardware is detected but,
for some reason, weird things still happen (e.g. audio sink muted).
https://phabricator.endlessm.com/T12455
> eos-diagnostic: Add and "Audio info" section with the output of pactl list

- eos-tech-support/eos-convert-system-qa
Fix eos-convert-system-qa to handle authentication for dev repos and make it use origin.ostree.endlessm.com as the host.
https://phabricator.endlessm.com/T3784
> Use origin.ostree.endlessm.com for ostree

- eos-core-depends
This reverts commit 9f9bce37cc18044fae3aa4dd6686228944e91f2e.
Like the original commit says, this was only needed for turtleblocks,
which does not depend on core OS components anymore.
Conflicts:
eos-core-depends
https://phabricator.endlessm.com/T12527
> Revert "Add explicit dependency on python-dbus"

- eos-core-depends
It's not supported in Chromium anymore.
https://phabricator.endlessm.com/T12638
> Remove icedtea-plugin from core OS

- eos-platform-runtime-depends
This is needed for apps like Frostwire.
https://phabricator.endlessm.com/T12539
> runtime: add openjdk-7-jre

- eos-tech-support/eos-convert-system
To properly share objects with ostree, /var/lib/flatpak is a symlink to
/sysroot/flatpak. Since /sysroot will become /, point the symlink to
/flatpak instead.
https://phabricator.endlessm.com/T12238
> eos-convert-system: Handle /var/lib/flatpak symlink

- eos-tech-support/eos-convert-system-qa
If run with the option to change the ostree to staging,
change the interval for checks from 14 days to 0.
https://phabricator.endlessm.com/T12749
> eos-convert-system-qa: check staging ostree daily

- eos-tech-support/eos-convert-system-qa
The ostree refs have been changed so that the branch is the last
component of the ref. Construct the full version (eos3.0 vs the original
eos3) and make it the last component want converting to the dev repo.
https://phabricator.endlessm.com/T12778
> eos-convert-system-qa: Use new ostree branch format

- os-depends
This is not only useful for setting up encryption for local partitions,
but also to access external encrypted drives, so it would be interesting
to add it (e.g. I backup to an encrypted USB Hard Drive).
https://phabricator.endlessm.com/T12451
> core: Add crypsetup, needed to support LUKS based encryption

- eos-platform-runtime-depends
This is needed to supply gvfs-open (called by default by xdg-open on GNOME
system), in T12251 we use it for Dropbox, but it's probably usefull for
other apps.
https://phabricator.endlessm.com/T12251
Signed-off-by: Niv Sardi <xaiki@evilgiggle.com>
> Add gvfs-bin to the Endless Runtime,

- eos-tech-support/eos-launch-all
Although this is technically a flatpak "app", it is actually
just a helper and does not have an executable, so let's skip it.
https://phabricator.endlessm.com/T12824
> eos-launch-all: exclude EknServices

- eos-tech-support/eos-convert-system-qa
Commit b2d1158a66365d3c2b6deda8423f54b136da12b8 fixed this for
eos-convert-system, but not for eos-convert-system-qa.
> Fix coredump generation for eos-convert-system-qa

- base-depends
- eos-core-depends
- eos-platform-runtime-depends
Two of these are only needed for applications, so let's put them in the
runtime. The WQY font is used for Chinese, so let's share between both
runtime and core OS.
https://phabricator.endlessm.com/T13052
> Move fonts package back to runtime

- base-depends
This was lost at some point during the package reorganization.
https://phabricator.endlessm.com/T12866
> base-depends: add sound-theme-freedesktop

- eos-tech-support/eos-check-secureboot
- eos-tech-support/eos-convert-system
For some reason (apparently a firmware problem, since a BIOS update for the Brix fixes this) the SecureBoot EFI var is not exported to userspace on the Mission. Ubuntu exports this information in `/proc`, so we can use it instead and get rid of `eos-check-secureboot` altogether.
https://phabricator.endlessm.com/T13009
> Use /proc/sys/kernel/secure_boot instead of EFI vars to check for secure boot

- eos-core-depends
This is a necessary service for the Mission image. As its using the
same eos ostree, it needs to be added to the core-depends.
https://phabricator.endlessm.com/T13178
> core-depends: add showmehow service

- eos-sdk-runtime-depends
Provided that the runtime metapackage contains the corresponding JRE package (`openjdk-7-jre`), it just seems fitting to add this to the SDK.
https://phabricator.endlessm.com/T13393
> Add openjdk-7-jdk to the SDK metapackage

- eos-tech-support/eos-diagnostics
For code that uses DMI info to match specific systems, the most common
fields used are sys_vendor and product_name together.
sys_vendor was not being reported here, add it.
@cosimoc can you take a quick look?
> eos-diagnostics: add sys_vendor value

- eos-tech-support/eos-diagnostics
By listing the contents of /var/lib/codecs, we can easily see
which keys are installed and which codecs have been decrypted.
https://phabricator.endlessm.com/T13401
> eos-diagnostics: include codecs info

- eos-tech-support/eos-diagnostics
Note that we try to get the attributes for both '/sysroot' (for OSTree)
and '/' (for converted systems).  There is no line feed on the output,
so we just assume that one will silently fail and print nothing.
https://phabricator.endlessm.com/T13465
> eos-diagnostics: add Endless image details

- eos-sdk-runtime-depends
We need it to build other projects when using Flatpak.
https://phabricator.endlessm.com/T13441
> Add cmake to the SDK runtime

- eos-tech-support/eos-write-image
A user reported trouble running this script. It appears they were not passing it any arguments; so let's make that error case a little more explicit.
> eos-write-image: clarify usage message

- eos-core-depends
From now on, eos-chrome-plugin-updater will be installed both on Intel
and ARM architectures, so there's no need for this differentiation.
https://phabricator.endlessm.com/T13597
> Stop including eos-chrome-plugin-updater-s3 in the base core image

- eos-sdk-runtime-depends
This is needed for building webkit for com.endlessm.programming.
> Add libwebp-dev to com.endlessm.Sdk

- eos-tech-support/eos-convert-system
The /var/lib/flatpak symlink is changed after everything has been copied
to /sysroot. So, changing the running /var/lib/flatpak has no effect
after rebooting. Check and change the correct symlink in
/sysroot/var/lib/flatpak.
https://phabricator.endlessm.com/T13478
> eos-convert-system: Operate on the correct /var/lib/flatpak

- eos-sdk-runtime-depends
These are still needed to build eos-metrics and eos-sdk in order to make
the custom version of eos-programming.
> More com.endlessm.Sdk dependencies

- eos-core-depends
- eos-installer-meta-depends
- eos-tech-support-depends
This depends on [corresponding packaging
changes](https://github.com/endlessm/eos-installer/pull/23) to split the parts
of eos-installer which conflict with gnome-initial-setup into a new package,
eos-installer-standalone.
https://phabricator.endlessm.com/T12548
> Include eos-installer in normal images

- os-depends
For amd64, prefer the linux-signed-image variant, which contains the
kernel signed for UEFI.
https://phabricator.endlessm.com/T12944
> os-depends: Prefer linux-signed-image on amd64

- eos-tech-support/eos-list-users
- eos-tech-support/eos-reset-password
The hard-coded /dev/sda2 is no longer valid for eos3.
Instead, let's list all users on all ostree devices,
and then require the user to explicitly specify the device
that contains the user whose password is to be reset.
With these changes, we now support split disks, too.
https://phabricator.endlessm.com/T6324
> eos-list-users / eos-reset-password: Update for eos3

- eos-tech-support/eos-convert-system
This reverts commit cab6e9bfb678f888f0e989df4c21023b39227e35.
Now that we are producing packages for signed kernels and bootloader, it
is possible to have a converted system under secure boot.
https://phabricator.endlessm.com/T13811
> Revert "eos-convert-system: Check if we're running under secure boot"

- eos-tech-support/eos-convert-system
This directory is vestigial in 3.0.x ostrees, and no longer exists in
3.1.x ostrees; so trying to merge it to /sysroot/endless is guaranteed
to fail.
https://phabricator.endlessm.com/T13832
> eos-convert-system: drop /endless

- eos-core-depends
This is an invaluable debugging tool and is only roughly 350 kB. We
already include gdb in eos-core, which is quite a bit bigger. It
probably makes sense to put them both in os-depends so that they're
available everywhere, but this is good enough for now.
https://phabricator.endlessm.com/T14123
> eos-core: Include strace

- eos-tech-support/eos-diagnostics
We currently collect hardware info manually and populate wiki pages for each supported product.
With the increased number of 3rd party products, we need something more scalable and we need an easy way of receiving this info from 3rd parties.
Add a new mode to eos-diagnostics which only outputs information relevant to hardware enablement efforts, and output in a more organised format (1 file per information item, in a tar archive). This also organises the information a bit better in the standard mode and adds more information to the dumps.
https://phabricator.endlessm.com/T14154
> eos-diagnostics: Add hardware info dump mode

- eos-tech-support/eos-diagnostics
Add CPU information to the regular and hardware dumps.
@cosimoc can you review this please? should be ultra quick
> eos-diagnostics: dump CPU info

- eos-tech-support/eos-reset-password
Somehow I must have inadvertantly tested on a non-ostree system
when I cleaned up for eos3 / split disk support, as the script
is broken when assuming that /etc is available directly under
the mount point.  Instead, bring back the logic that used ostree
admin to find the currently deployed directory.
https://phabricator.endlessm.com/T14303
> eos-reset-password: fix for ostree systems

- os-depends
Initially this will used be in the image builder so that it can
intelligently query flatpak instead of scraping the CLI output. However,
I can also see it being useful for providing flatpak support scripts in
the future. E.g., to change the default branch when upgrading from eos3
to eos4.
Only the python3-gi support is currently needed for the image builder,
and it's already pulled into eos-core. However, the OS already includes
both python 2 and python 3. The GI support packages are less than 1 MB,
so it seems nice to be able to use GIR from whichever python version is
preferred.
https://phabricator.endlessm.com/T14224
> os: Include support for flatpak python GIR bindings

- eos-tech-support/eos-list-users
- eos-tech-support/eos-reset-password
- eos-tech-support/eos-uninstall-dualboot
I'm not particularly happy with the code duplication here. One option would be
to merge the two scripts (and preferably rewrite it in Python in the process --
I had some nasty scoping problems with the cleanup hooks).
https://phabricator.endlessm.com/T14302
> eos-{list-users,reset-password}: support dual-boot installations

- eos-core-depends
In bluez-5.25 this was provided by bluez-obexd and in the latest
version, that Provides has been removed. Switch to using the real
package name.
https://phabricator.endlessm.com/T14411
> eos-core-depends: stop using old virtual obexd-client

- eos-tech-support/eos-convert-system
We are generating /etc/sysctl.d/50-coredump.conf in the OSTree
deployment instead of the root partition's root, so it has no effect in
converted system after reboot. This points it directly to /sysroot.
https://phabricator.endlessm.com/T14497
> eos-convert-system: Enable coredump genation in sysroot

- eos-core-depends
For the coding project we have packages a set of shell extensions that should be integrated into the image.
> Add coding-shell-extensions to the image

- eos-core-depends
GNOME Builder will not be able to build flatpaks, this is needed by the CodeView feature.
> Coding, CodeView: needs flatpak-builder to be present

- eos-tech-support/eos-convert-system-qa
Probabaly the result of overly enthusiastic copy-pasting.
> Fix typo in echo statement in eos-convert-system-qa

- eos-core-depends
The Telepathy packages were removed in the past because
Empathy itself wasn't very used. With the upcoming GNOME
repositories enabled by default, however, Polari will
require Telepathy - and will fail without absolutely
no error message if Telepathy isn't there.
To make Polari work properly and avoid further frustrations,
add Telepathy (but not Empathy) back.
https://phabricator.endlessm.com/T14703
> core: add telepathy packages

- eos-tech-support/eos-write-live-image
'true' and 'false' are not bash built-ins.
Signed-off-by: Carlo Caione <carlo@endlessm.com>
> eos-write-live-image: Fix boolean check

- eos-tech-support/eos-convert-system-qa
The awk command was incorrect because there are an arbitrary number
of words in between the repo name and the url, so trying to extract
the url from that line was giving us incorrect results. Instead
let's just hardcode the repo names since they aren't going to change
anytime soon.
> Get repo urls from ostree call, rather than from awk parsing

- eos-tech-support/eos-download-image
- eos-tech-support/eos-write-live-image
Add --personality and --product arguments to eos-write-live-installer, and make eos-download-image select the fnde_aluno personality (rather than base, which doesn't exist) if the fnde product is requested.
https://phabricator.endlessm.com/T15135
> allow eos-write-live-installer to be used by FNDE

- eos-tech-support/eos-download-image
Fix running the eos-download-image script on older distros.
https://phabricator.endlessm.com/T15135
> eos-download-image: handle python <3.3 by making shlex.quote use optional

- eos-platform-runtime-depends
Added mali dependency on flatpak runtime
https://phabricator.endlessm.com/T15102
> eos-platform-runtime-depends: added mali drivers dep

- eos-tech-support/eos-download-image
Rather than downloading a single image, add a mirror mode to eos-download-image that downloads all released images for a product. This will outside organizations to host a mirror of the Endless images.
https://phabricator.endlessm.com/T15116
> Add mirror mode to eos-download-image

- eos-sdk-runtime-depends
flatpak-builder tries to run appstream-compose in the sandbox when
finishing apps. Include appstream-util in eos-sdk-runtime so that
com.endlessm.Sdk has appstream-compose.
https://phabricator.endlessm.com/T14935
> eos-sdk-runtime: Include appstream-compose

- eos-tech-support/eos-write-live-image
This adds a --label argument to eos-write-live-image in ISO mode, so that we can set more useful labels for the volume, visible under Windows, Mac and Linux. Also adds an autorun.inf to execute the installer automatically if the ISO is on an optical disk which is inserted on a Windows machine.
https://phabricator.endlessm.com/T14986
> T14986: set the ISO volume ID and add autorun.inf

- eos-tech-support/eos-download-image
Our innovation of a 4-part image version number is outside the permitted
definitions that distutils.StrictVersion will accept.
https://phabricator.endlessm.com/T15390
> eos-download-image: switch from StrictVersion to LooseVersion

- eos-tech-support/eos-write-live-image
Removes "-volid text does not comply to ISO 9660 / ECMA 119 rules" error
from xorisso and should improve compatibility.
https://phabricator.endlessm.com/T14986
> remove . from permitted strings in ISO volume ID

- eos-tech-support/eos-write-live-image
If we are making an ISO, we uncompress the image file into a tmpdir
before creating the squashfs. In the case the source image is
uncompressed, eos-write-image ends up being a used as a slow version
of cp. This optimisation attempts to hardlink the file in the hope
that the source image and tmpdir are on the same device, but otherwise
falls back to the previous code.
https://phabricator.endlessm.com/T15394
> eos-write-live-image: optimisation for uncompressed .img source file

- eos-tech-support/eos-write-image
- eos-tech-support/eos-write-live-image
Lots of people assume you can call these the same way:
eos-write-image IMAGE DEVICE
eos-write-live-image IMAGE DEVICE
but the latter is wrong, and gives this confusing error:
$OUTPUT does not exist or is not a block device... aborting!
The correct syntax is more like:
eos-write-live-image DEVICE --os-image IMAGE --latest
In both cases, let's check the arguments more strictly and give better
error messages.
https://phabricator.endlessm.com/T15285
> write-[live-]image: error if too many arguments given

- os-depends
This package has been merged into the main pulseaudio package.
https://phabricator.endlessm.com/T14580
> os: Remove pulseaudio-module-x11

- eos-tech-support/eos-write-live-image
In both paths above, we have just written a new partition table to
$OUTPUT, then run `udevadm settle` and `partprobe $OUTPUT`. We still
need to let udev catch up after probing the new partition table but we
don't need to trigger a probe of all devices in the system.
If you have an Endless OS ISO attached to the system (on a different
device to $OUTPUT), the script would fail here:
Warning: Unable to open /dev/sr0 read-write (Read-only file system).
/dev/sr0 has been opened read-only.
Warning: Unable to open /dev/sr0 read-write (Read-only file system).
/dev/sr0 has been opened read-only.
Error: Invalid partition table - recursive partition on /dev/sr0.
It's true that our ISOs have a weird partition table containing a
partition which spans the whole device; but it's irrelevant when we're …
> write-live-image: remove redundant 'partprobe'

- eos-tech-support/eos-write-live-image
Once the SquashFS image is created, we don't need the original image at
all. This is intended for use on the image builder, where there is not
enough disk space for the uncompressed image, the SquashFS image, and
the ISO image all at the same time.
(Note that we already delete the uncompressed copy of the image in
$DIR_IMAGES_ENDLESS. In the image builder case, this is a hardlink to
$OS_IMAGE.)
https://phabricator.endlessm.com/T15668
> write-live-image: add --delete-os-image flag

- eos-core-depends
This contains the eos-updater-ctl and eos-updater-prepare-volume tools,
which can be useful for manually running the updater and preparing USB
drive updates for larger (or non-network connected) deployments.
https://phabricator.endlessm.com/T15895
> eos-core-depends: Add eos-updater-tools

- eos-core-depends
This will be needed for replicating KA Lite installations from one
machine into multiple destinations, both the flatpak and the data.
https://phabricator.endlessm.com/T15449
> eos-core Add eos-kalite-tools

- eos-tech-support/eos-convert-system
- eos-tech-support/eos-convert-system-qa
- eos-tech-support/eos-dev-fix
The eos-updater unit files changed recently (eos-updater.service was
created, having previously been an alias for eos-autoupdater.service).
Update the tech support scripts to reflect this.
Additionally, the configuration file locations for eos-updater changed:
/etc/eos-updater.conf moved to /etc/eos-updater/eos-autoupdater.conf.
https://phabricator.endlessm.com/T15977
> eos-tech-support: Port eos-updater service handling to latest unit files

- os-depends
The well-intentioned grub-efi-amd64-image-signed | grub-efi-amd64-image which was handy for development means we can accidentally build ostrees without a signed grub EFI binary, depending on the state of the package archives, signing servers, etc. Remove this possibility.
https://phabricator.endlessm.com/T16069
> T16069: permit only signed grub on amd64 ostrees

- os-depends
Ensure we don't have a configuration where eos-meta can be installed on amd64 with an unsigned kernel image.
https://phabricator.endlessm.com/T16069
> T16069: remove possibility of unsigned kernel on amd64

- eos-tech-support/eos-download-image
This is a regression introduced in 42c0d01. eos-write-live-image expects
this script to print the path to the newly-downloaded file to stdout,
when called with --latest.
Without this fix, `eos-write-live-image` without an explicit
--windows-tool argument will fail.
https://phabricator.endlessm.com/T16099
> eos-download-image: print path to Windows tool

- eos-tech-support/eos-write-live-image
This doesn't make the problem go away in the case where you write a new MBR/GPT to disk A (in the terminology of this patch) using some other tool, of course, but it's a start.
https://phabricator.endlessm.com/T16428
> eos-write-live-image: zero out old ISO9660 header

- eos-platform-runtime-depends
gcompris was the final user of gst0.10, and it's now using gst1.0
https://phabricator.endlessm.com/T11462
> Endless runtime: remove gstreamer-0.10

- eos-sdk-runtime-depends
This is to allow running gtk3-widget-factory as a dev tool.
https://phabricator.endlessm.com/T16555
> Add gtk-3-examples to com.endlessm.Sdk

- eos-tech-support/eos-diagnostics
The file is no longer generated, and we can determine the
personality from the image name.
https://phabricator.endlessm.com/T17029
> eos-diagnostics: Don't check for personality file

- eos-tech-support/eos-rollback
This script reverts to the previously deployed OSTree,
in the case that the new OSTree can be booted but has a
critical problem that makes it unusable (e.g., broken WiFi).
https://phabricator.endlessm.com/T16972
> tech support: add eos-revert-ostree

- os-depends
It's required to specify the version of gnome-shell or eos-shell
won't get removed in existing installations, as it also provides
the 'gnome-shell' package.
https://phabricator.endlessm.com/T17155
> Replace dependency on eos-shell with gnome-shell (>= 3.22.3)

- debian/control
- eos-core-nexthw-depends
For nexthw builds, the ostree builder will use the "nexthw" platform,
so we need an appropriate core package. Add one that is just a simple
reference to the standard eos-core-amd64.
https://phabricator.endlessm.com/T15591
> Add eos-core-nexthw package

- os-depends
This is a script which downloads Broadcom proprietary Linux drivers from
the web, extracts the firmware files needed by the open source drivers
from the proprietary drivers, and install the firmware files in the
right place.
eos-b43fw-clean is also provided by the same package to uninstall these
files, if needed.
https://phabricator.endlessm.com/T12154
> Install eos-b43fw-install

- base-depends
- eos-platform-runtime-depends
- add gstreamer1.0-plugins-ugly-lame package to the base depends
(for Rhythmbox and any other GStreamer apps in the OS/runtime)
- add libmp3lame0 explicitly to the runtime for Audacity (effectively
redundant with the above, but more explicit/strictly correct)
https://phabricator.endlessm.com/T16932
> enable MP3 encoding in the OS

- eos-core-depends
https://phabricator.endlessm.com/T13612
> eos-core-depends: add gnome-logs

- eos-tech-support/eos-list-users
Without these changes:
```
live@endless:~$ sudo eos-list-users 
FUSE exfat 1.2.3
WARN: '/dev/sdb1' is write-protected, mounting read-only.
fuse: mount failed: Device or resource busy
```
With these changes:
```
live@endless:~$ sudo ~/src/endlessm/eos-meta/eos-tech-support/eos-list-users 
Users on /dev/sda3:
guybrush  shared  wjt
```
I am open to alternative suggestions for how to skip the booted image host partition and mapped ostree partition, but the read-only flag seems the most straightforward to me!
https://phabricator.endlessm.com/T17560
> eos-list-users: work correctly on live USBs

- eos-tech-support/eos-diagnostics
We have a few user support issues where we see the wifi blocked,
but it's not clear if its software- or hardware-blocked nor what
exactly is behind it.
Now we log each rfkill device, name, type, and driver, and:
1. soft
Whether it has been blocked in software (and hence can be unblocked)
2. hard
Whether something in the hardware has blocked it (can't be unblocked in
software)
3. persistent
Whether the soft-blocked state is initialiased from non-volatile storage
These are all well documented in the kernel's ABI documentation.
https://phabricator.endlessm.com/T17620
> eos-diagnostics: log rfkill devices and state

- os-depends
This package will set the version number in /etc/os-release
from this point onwards.
https://phabricator.endlessm.com/T17633
> os-depends: add eos-version-number

- eos-tech-support/eos-write-image
The heuristics available from lsblk to detect removable media are:
* RM: matches the 'removable' attribute in sysfs. This is 1 for all
USB sticks I have handy, 0 for the removable SD card inserted
into my laptop, and 0 for a soldered-in MMC in at least one other
laptop.
* HOTPLUG: 1 if RM is 1, or if the device chain includes a USB,
IEEE1394, PCMCIA, MMC or CCW device. This is 1 for all devices
mentioned above.
As discussed at https://phabricator.endlessm.com/T17871#409848
https://bugs.freedesktop.org/show_bug.cgi?id=49844 and elsewhere, these
heuristics are imperfect but we cannot do much better.
If we falsely believe a fixed device (eg soldered-on MMC) to be
removable, we will rely on the firmware loading the default boot path
\efi\boot\bootx64.efi for every boot. (This is what we did …
> eos-write-image: detect removable media automatically

- eos-core-depends
- os-depends
network-manager-openvpn apparently doesn't work without -openvpn-gnome, so it's better to depend
on that one directly, similar to -vpnc-gnome which we already have.
Also found a bunch of other things which weren't necessarily in the right place os-depends (shared with eos-installer) vs eos-core.
https://phabricator.endlessm.com/T17912
> fix inclusion of OpenVPN support

- eos-tech-support/eos-uninstall-dualboot
This script is now useless for all newly-installed systems, but it
features in our documentation and may still be useful in emergencies on
older installations.
https://phabricator.endlessm.com/T17048
> eos-uninstall-dualboot: detect eosldr and fail gracefully

- eos-core-depends
- eos-language-pack-ar-depends
- eos-language-pack-bn-depends
- eos-language-pack-de-depends
- eos-language-pack-en-depends
- eos-language-pack-es-depends
- eos-language-pack-fr-depends
- eos-language-pack-id-depends
- eos-language-pack-pt-br-depends
- eos-language-pack-pt-depends
- eos-language-pack-ro-depends
- eos-language-pack-th-depends
- eos-language-pack-vi-depends
- eos-language-pack-zh-cn-depends
- eos-language-pack-zh-tw-depends
libreoffice is not buildable on current master, and the plan is
to move it into a flatpak for EOS-3.3.
https://phabricator.endlessm.com/T14879
> Drop libreoffice from core packages

- eos-tech-support/eos-rollback
Rather than switch to the deployment that is not currently booted,
we change the default boot order.  This way, if the user has to
go into the GRUB menu to boot into the previous deployment,
he/she can still use eos-rollback to persist this old deployment.
Each call to this script rotates the boot order for the available
deployments, putting the first deployment to the end of the list.
In the case of Endless OS, there are only two deployments,
so we effectively toggle between the two available versions.
The implementation is migrated from awful command-line parsing
in bash to a clean python script provided by Dan Nicholson.
With the python API, we no longer have to redeploy, so the process
is much faster.
https://phabricator.endlessm.com/T18539
> eos-rollback: Rollback even if the old deployment is booted

- eos-core-depends
https://phabricator.endlessm.com/T16839
> eos-core: eos-google-chrome-helper was renamed

- eos-core-depends
The Google Chrome helper functionality is being reinstated in the
eos-browser-tools package, so we need both binary packages now.
https://phabricator.endlessm.com/T16839
> add eos-google-chrome-helper as a separate package

- eos-dev-depends
The endless-ca-cert package provides the Endless SSL CA root certificate
and includes it in the system trusted store. This certificate is to sign
SSL certificates for internal Endless services. See
https://phabricator.endlessm.com/w/sysadmin/ssl-ca/ for details.
https://phabricator.endlessm.com/T18743
> eos-dev: Include endless-ca-cert

- base-depends
These APIs are now provided by packages built from libglvnd source
package:
- libegl1   replaced  libegl1-mesa
- libgles2  replaced  libgles2-mesa
- libgl1    replaced  libgl1-mesa-glx
- libglx0   replaced  libgl1-mesa-glx
libegl1-mesa-drivers was a leftover from a previous mesa, and should
have been replaced with libegl1-mesa.
https://phabricator.endlessm.com/T18579
> base-depends: Update EGL and GLES2 dependencies

- eos-tech-support/eos-fix-ostree-repo
This script attempts to fix the two primary issues we've seen with
missing objects in /ostree/repo:
1. If the deleted object is part of a commit, then the commit is now
partial, but OSTree doesn't know that unless a commitpartial file
exists. Without that, it will assume the commit is fully intact and use
it as the source for a static delta.
2. If the deleted object is a commit, then any references to it will be
dangling. This will cause errors since OSTree assumes that a referenced
commit will exist and will raise errors as soon as it tries to be used.
This script attempts to address these 2 issues by repulling the commits
for any dangling references and marking any commits with missing objects
as partial.
To guard against another program operating on the repository, all
processes that …
> eos-tech-support: Add eos-fix-ostree-repo script

- eos-tech-support/eos-download-image
Without this change, running `eos-download-image --product esodvd` gives
you a long traceback followed by:
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
With this change, you get a more human-readable error describing the
actual cause:
Couldn't fetch manifest for product esodvd
403 Client Error: Forbidden for url: https://d1anzknqnc1kmb.cloudfront.net/releases-esodvd-3.json
Found while QAing https://phabricator.endlessm.com/T18653
> eos-download-image: handle missing manifest gracefully

- debian/control
- eos-tech-support-iso-depends
- eos-tech-support/eos-write-image
- eos-tech-support/eos-write-live-image
ISO generation now lives in the image builder.  It was never possible to run this mode on an unconverted Endless OS system, since several of the dependencies are not included in the ostree.
I also tidied up a few things I noticed along the way.
https://phabricator.endlessm.com/T17203
> eos-write-live-image: remove --iso, cleanup

- eos-tech-support/eos-convert-system-qa
Previously, systemd-coredump would be enabled on the next boot, but not
during the current boot. I hit an eos-updater SIGSEGV while pulling an
update after running `eos-convert-system-qa --ostree` and it would have
been nice to get a core dump.
> convert-system-qa: set core_pattern immediately

- eos-tech-support/eos-fix-ostree-repo
Unfortunately, the script was only catching when a `dirtree` object was missing, not a `dirmeta` or `file` object. That meant that in many cases the commit wasn't being marked as partial and the script carried on without refetching missing objects.
I also added one more commit to skip pulling full Locale commits as flatpak intentionally does partial pulls of those. Pulling the full commit would just waste bandwidth and disk space.
I tested this in a VM where I deleted all types of missing objects. After running the script, `ostree fsck` succeeded, I was able to update to update the platform, and I was able to install an app.
https://phabricator.endlessm.com/T18946
> ostree-fix-repo: Improve check for partial commits

- eos-tech-support/eos-fix-ostree-repo
The ostree on eos3.0 has a couple issues that make the script fail. Add some workarounds for them and a message at the end so they know if it worked or not.
https://phabricator.endlessm.com/T19420
> eos-fix-ostree-repo workarounds for old OSTree

- eos-tech-support/eos-fix-ostree-repo
Add a --repo option to eos-fix-ostree-repo so that split system flatpak repos can be fixed.
https://phabricator.endlessm.com/T18946
> Fix non-system flatpak repos

- base-depends
With GLVND, we have libglx0 provided by libglvnd, which is provides de
API and dispatch library for applications. It depends on
'libglx-mesa0 | libglx-vendor', and libglx-vendor is provided by both
libglx-mesa0 and libglx-nvidia0.
After adding the nvidia proprietary drivers, we are pulling
libglx-nvidia0 as a dependency of libgl1-nvidia-glvnd-glx, so we could
fall into a situation where libglx-mesa0 is missing because libglx0's
dependency is already satisfied by libglx-vendor through libglx-nvidia0.
This has been seen on eos-converted systems, but on on OSTree-based
systems so far, although that was probably pure luck.
Explicitly installing libglx-mesa0 should guarantee we always have both
libraries installed.
https://phabricator.endlessm.com/T18579
> Explicitly install libglx-mesa0

- eos-tech-support/eos-diagnostics
Before:
Gjs-Message: JS LOG: Saved to /sysroot/home/wjt/eos-diagnostic-171103_144228_UTC
+0000.txt
(This message is too long for the default width of the terminal, even
with my short username; I have indicated how the line is wrapped in
practice.)
After:
Endless OS Diagnostics file saved as:
/sysroot/home/wjt/eos-diagnostic-171103_144325_UTC+0000.txt
Please send that file (not this message!) to the Endless Community or Support.
and Nautilus pops up, with the file already highlighted.
I tried to use `Gtk.RecentManager.get_default().add_item(filename)` to add
it to the Recent tab in Nautilus and the file picker, but no dice.
https://phabricator.endlessm.com/T19833
> eos-diagnostics: reveal created file, be friendlier

- os-depends
This is needed to enable some app-specific workarounds, fixing a
gnome-shell flicker on Asus GL702VMK.
https://phabricator.endlessm.com/T19768
> os-depends: add nvidia-driver-bin

- eos-tech-support/eos-add-to-desktop
And display the basename of the script in the usage, not the entire
path.
> eos-add-to-desktop: Display usage for -h, --help

- eos-tech-support/eos-download-image
For Solutions images we don't want to publish an index of them all, but
we still need to be able to download them using e-d-i. So add --url and
--size arguments so the process of checking a manifest can be
circumvented.
https://phabricator.endlessm.com/T20033
> eos-download-image: Allow download from URL

- eos-tech-support/eos-write-installer
pv is used, so warn the user if it's not installed.
> eos-write-installer: Check for pv dependency

- eos-tech-support/eos-convert-system
- eos-tech-support/eos-convert-system-qa
- eos-tech-support/eos-enable-coredumps
The new command fixes a problem in the current way coredumps were meant to
be enabled, which did not work because (1) eos-metrics-instrumentation would
override the kernel.core_pattern setting and (2) coredumps would be still
disabled due to the default 0-byte size limit set in limits.conf.
Besides, having a separate command makes it more convenient to enable
coredumps in non-converted systems.
https://phabricator.endlessm.com/T20331
> New eos-enable-coredumps command, reused it from eos-convert-system scripts

- eos-tech-support/eos-enable-coredumps
Somehow I overlooked this situation while testing and the current
code is broken due to $1 being an unbound variable in that case.
https://phabricator.endlessm.com/T20331
> eos-enable-coredumps: Fix usage with no parameters passed

- eos-tech-support/eos-diagnostics
As we work with more dual GPU systems, it would be useful for
eos-diagnostics to log info about DRM connectors.
For example, this allows us to easily see which display output is connected
to which GPU.
https://phabricator.endlessm.com/T20578
> eos-diagnostics: Log DRM connector info

- debian/control
Starting with WebKit2GTK 2.18.4, we're getting rid of the epoch
added to WebKit packages since version 2.6.2, so make an explicit
conflict here so that such versions are never pulled for OSTree
based images, as well as to warn "users" of converted systems that
manual intervention (downgrading from 1:2.18.3 to 2.18.4) is required.
https://phabricator.endlessm.com/T20629
> Conflict on WebKit packages with an epoch set

- os-depends
This is an ubuntu-specific package but we are switching to the
Debian version of xkeyboard-config, where these i18n data files are
included in the regular xkb-data package which we already ship.
https://phabricator.endlessm.com/T20508
> os-depends: drop xkb-data-i18n

- eos-core-depends
Endless OS does not use btrfs.
https://phabricator.endlessm.com/T20709
> core: remove btrfs-tools

- base-depends
- eos-core-depends
- os-depends
We are moving to not installing recommended packages in the ostree
builder.
However, we do ship some important packages via the Recommends
mechanism. Add explicit dependencies on these packages here, so that
they continue to be shipped.
https://phabricator.endlessm.com/T5124
> Add previously-recommended packages to core

- debian/defaults.list
This patch sets GNOME Software as the default application for opening
ostree repos in removable drives. It should result in GNOME Software
opening by default when when a USB containing an ostree repo is
inserted.
https://phabricator.endlessm.com/T16950
> defaults: Associate GNOME Software with ostree repos

- eos-tech-support/eos-convert-system
When launched, this program prints the following warning:
> Deprecated program in use: rename as shipped with the Debian perl
> package will be removed after the release of stretch. Please install
> the separate 'rename' package which will provide the same command.
Rather than pull in this extra dependency just for the benefit of this
script, replace it with a few rounds of Bash parameter expansion.
https://phabricator.endlessm.com/T21179
> eos-convert-system: do not use rename(1)

- eos-tech-support/eos-diagnostics
The 5 in parameters are working_directory, argv, envp, flags and
child_setup.  The 6th argument in C is user_data for the child_setup()
function but this is not applicable from JS.
https://phabricator.endlessm.com/T21220
> eos-diagnostics: remove stray argument to GLib.spawn_sync()

- eos-core-depends
This is a recommends of systemd-sysv, and it is needed so users and
groups created by units with DynamicUser= can be resolved by NSS.
Installing this package automatically adds the module to
/etc/nsswitch.conf.
https://phabricator.endlessm.com/T21201
> eos-core-depends: Add libnss-systemd

- os-depends
Found xserver-xorg-video-fbdev - X.Org X server -- fbdev display driver is
missed in the master image.  The driver is needed for efifb.
If this is missed, the X will be black screen with the nouveau driver which goes
with parameters noaccel=1 modeset=0
Therfore, we need to add fbdev back.
https://phabricator.endlessm.com/T21555
> os-depends: Add X fbdev driver

- eos-tech-support/README.md
- eos-tech-support/eos-procmem-sample
- eos-tech-support/eos-sysmem-sampler
- eos-tech-support/eos-user-stress-test
This adds a few tools for measuring aggregate system memory metrics, PSS and RSS memory usage of processes on the system (aggregated by command), and producing stress on a system in ways we might expect users to stress it.
These are designed to produce output suitable for plugging into specially-formatted spreadsheets for analysis and archiving.
NOTE: this commit adds some test files (one of which is nearly 10 MiB). It's generally not good practice to include large data files in git, so please let me know if you'd like to separate them out into a different location. I would definitely recommend against continuing to add files in this git repo and if we avoid it now we can prevent a "git clone" of this repo from always being significantly larger than it would be otherwise.
> Stress mem tools

- eos-tech-support/eos-stage-flatpak
As this command directly acts on the system ostree repo, if flatpak lists any user remotes, it fails.
> eos-stage-flatpak: avoid failure when --user repos are configured

- eos-core-depends
It is not included by default on libgdk-pixbuf2.0-0
anymore, and no package has a strong dependency on
it.
https://phabricator.endlessm.com/T22015
> core: Add GDK Pixbug thumbnailer

- eos-tech-support/eos-diagnostics
By default, exclude journal records before the previous and current
boot.
This is to reduce the amount of potentially-private information exposed
by default as we will shortly enable persistent storage by default (for
systems with durable storage devices).
https://phabricator.endlessm.com/T21771
> Only include the previous and current boot in journal

- eos-core-depends
It was added for gnome-sushi which is relatively rarely used. I will
patch it to invoke unoconv via flatpak in a separate ticket.
https://phabricator.endlessm.com/T22113
> remove unoconv from the core OS

- eos-core-depends
- eos-metapackage
Tidying a few loose ends from https://phabricator.endlessm.com/T22113 - due to the order of apt processing eos-core dependencies, aspell-en was being installed un-necessarily, myspell is deprecated in favour of hunspell, and we started shipping myspell-pt by mistake.
> T22113: tidy up spelling packages

- eos-core-depends
- os-depends
In line with our runtimes, try to limit our python2 exposure. Ideally we'd ship python3 only in the core OS, but let's see if python2 is still dragged in as a dep after this.
https://phabricator.endlessm.com/T22180
> Drop python2 modules

- eos-core-depends
This is recommended by brasero, and makes sense to include
as long as we have both brasero and nautilus in the core OS.
https://phabricator.endlessm.com/T21768
> eos-core-depends: add nautilus-extension-brasero

- eos-core-depends
https://phabricator.endlessm.com/T21074
> eos-core-depends: depend on imagescan-driver to avoid GTK2 dep

- eos-tech-support/eos-fix-ostree-repo
Our OSTree bindings currently expose OSTree.RepoCommitState
enums as NORMAL and PARTIAL, while we were using the old
value REPO_COMMIT_STATE_PARTIAL.
Fix that by using PARTIAL instead.
> eos-fix-ostree-repo: Use the correct enum name

- eos-core-depends
This package needs to be installed in the base OSTree so that the
cracklib's password database is installed, as it's required by
the password meter widget in the "password" page of g-i-s.
https://phabricator.endlessm.com/T22217
> eos-core-depends: Add cracklib-runtime, needed for gnome-initial-setup

- eos-tech-support/eos-enable-coredumps
Even if systemd-coredump is enabled, the default coredump size limit for
all systemd units is not infinite, and this prevents things like
eos-updater successfully dumping core, with the message:
systemd-coredump[1664]: Resource limits disable core dumping for
process 1573 (eos-updater).
This is frustrating.
Fix it by having eos-enable-coredumps add a systemd configuration file
which ups the default `ulimit -c` value for units to infinity.
See:
https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html
and
https://lists.freedesktop.org/archives/systemd-devel/2013-February/009174.html.
> eos-enable-coredumps: Set default `ulimit -c` value for systemd units

- debian/control
- eos-dev-depends
- eos-dev-suggests
- eos-metapackage
Add an explanatory comment in eos-dev-depends to explain what types of
packages should be listed there.
Remove the following packages which I assume do not meet these guidelines:
bison, bonnie++, elinks, flex, fluxbox, germinate, glade, gparted,
gperf, language-pack-*, lftp, libjson-glib-doc, locate, ltrace, moreutils,
nethogs, nmap, putty, sl, tig
gnome-api-docs is not present in the distro.
devhelp is available as a flatpak.
openssh-server and p7zip-full are included in the main distro
Switch pyflakes to python3 version
Philip C suggests that eos-node-modules-dev is probably not used
by anyone any more, since you can do node development on unconverted
systems.
Add some packages that I think should be here:
manpages, obs-build, pbuilder
Create and document a new eos-dev-suggests file, to …
> Update eos-dev dependencies

- eos-tech-support/eos-stage-ostree
The 3.3 to 3.4 transition included a checkpoint on the eos3 stable
branch redirecting to an eos3a stable branch for use on 3.4+. Add a case
to handle that.
https://phabricator.endlessm.com/T22478
> eos-stage-ostree: Handle eos3a stable branch used on 3.4+

- eos-tech-support/eos-enable-debian-apt
Sometimes, a developer tool is not available in OBS but it can be
installed from official debian packages without dependency headaches.
Add a developer-only script that adds apt config for the regular Debian
repos, configured in such a way that Endless stuff takes precedence.
Useful reading:
https://wiki.debian.org/AptPreferences
https://gist.github.com/JPvRiel/8ae81e21ce6397a0502fedddca068507
> Add developer script to enable Debian repo

- eos-core-depends
Split Flatpak auto-installation JSON files to architecture-independent
eos-flatpak-autoinstall package so they are included on ARM systems.
https://phabricator.endlessm.com/T22652
> flatpak-autoinstall: split to separate eos-flatpak-autoinstall package

- eos-tech-support/eos-uninstall-dualboot
We no longer include python 2 in the OS, but this dependency was not
declared in the package metadata.
This script is now obsolete for all but extremely old installations, but
we keep it around since it is small and referenced in our documentation
(eg https://support.endlessm.com/hc/en-us/articles/214475283).
https://phabricator.endlessm.com/T22670
> eos-uninstall-dualboot: use python3 not python (2)

- base-depends
- eos-core-depends
Nothing in the core OS requires GTK2 anymore.
https://phabricator.endlessm.com/T21074
> Remove GTK2 modules and themes

- base-depends
- eos-core-depends
Instead of gnome-themes-standard, which has an unwanted dependency
on GTK2.
https://phabricator.endlessm.com/T21074
> Depend on highcontrast-icon-theme

- eos-tech-support/eos-diagnostics
Since we seem to be getting more bug reports which concern incorrect
OSTree repository configurations, it’s probably useful to include the
contents of /ostree/repo/config in the diagnostics report.
Note that this means our repository passwords will be included in the
report, but since users can read them out of /ostree/repo/config anyway,
that’s probably not a problem.
Sample output:
===================================
= OSTree repository configuration =
===================================
[core]
repo_version=1
mode=bare
min-free-space-percent=0
add-remotes-config-dir=false
…
https://phabricator.endlessm.com/T22886
> eos-diagnostics: Add a section for /ostree/repo/config

- eos-tech-support/eos-diagnostics
Same as cbd5f777 but additionally capture the repo config file from
the Flatpak repo on the SD card on split systems.
https://phabricator.endlessm.com/T22886
> eos-diagnostics: also capture OSTree config from extra SD card

- eos-tech-support/eos-write-installer
Since util-linux 2.32, sfdisk detects when the secondary GPT is not at the end of the disk, and adjusts the header in the output of --dump accordingly so that if you run `sfdisk --dump $DEVICE | sfdisk $DEVICE` the GPT is extended to cover the entire device.
https://github.com/karelzak/util-linux/commit/9a8a3b88dcaec36d694aaea29d6fce5856d697c4
While this is helpful in general, it means we cannot use the last-lba header to work out where the exFAT partition should start. Instead, we can calculate it from the start and size of the final partition.
I got this wonderful regular expression from https://github.com/endlessm/eos-boot-helper/blob/a4dee04/dracut/repartition/endless-repartition.sh#L163
While I was here I fixed some shellcheck warnings.
https://phabricator.endlessm.com/T22943
> eos-write-installer: fix calculating exFAT partition start

- eos-core-depends
Required to enable reading encrypted USB devices.
https://phabricator.endlessm.com/T23046
> eos-core-depends: add libblockdev-crypto2

- eos-tech-support/eos-download-image
By default, requests.head() does not follow redirects, so the response
when trying to get the file size did not contain Content-Length.
images-dl.endlessm.com is currently a CNAME rather than a redirector,
but we should pre-emptively handle that case.
https://phabricator.endlessm.com/T16529
> eos-download-image: use images-dl.endlessm.com, handle redirects

- eos-core-depends
We have those available as flatpaks now. These can be removed.
I kept coding-shell-extensions, as that's independent, but we will
have to understand what to do there too.
https://phabricator.endlessm.com/T23278
> Remove coding dependencies from OSTree

- os-depends
We dropped support for the i686 architecture on EOS 3.0 and don't build
linux-image-generic-64 since then.
https://phabricator.endlessm.com/T23361
> os-depends: Drop leftover reference to linux-image-generic-64

- eos-tech-support/eos-diagnostics
While this largely duplicates the two `flatpak list` incantations, it
would have allowed us to notice sooner that the local:factory and
eos:eos2/i386 refs were still around on a system upgraded from eos2. We
could try to filter out known flatpak remotes from this list but it
doesn't seem worth it. OTOH it *does* seem worth sorting the list
because it's otherwise illegible.
https://phabricator.endlessm.com/T23443
> eos-tech-support: collect `ostree refs`

- eos-core-depends
This sets permissions on USB U2F tokens so they can be used by unprivileged processes.
I also alphabetized the few unalphabetized entries in this file, as a later patch in case we want to cherry-pick the functional change back to eos3.4.
https://phabricator.endlessm.com/T23496
> eos-core: add u2f-hidraw-policy

- eos-tech-support/eos-diagnostics
If eos-diagnostics is being called from outside a user session, there
will be no session bus and no $DISPLAY variable to auto-start one with,
so creating a proxy for the SessionManager will fail.
Catch and ignore that failure.
This is triggered when calling eos-diagnostics on OpenQA VMs.
> eos-diagnostics: Ignore failure to get the renderer without D-Bus

- eos-core-depends
This is not used by Endless Hack.
> eos-core-depends: remove coding-shell-extensions package

- os-depends
Previously, eos-paygd was pulled in as a dependency of gnome-shell; now,
we'll pull it in as a dependency of this as well.
https://phabricator.endlessm.com/T23606
> os-depends: depend on eos-payg-nonfree

- eos-tech-support/eos-fix-mbr-swap-removal
Move the `rm` calls to the very last moment possible, add `-f` to them
so they don't fail, and move the "partition table fixed" message before
udevadm.
https://phabricator.endlessm.com/T24493
> eos-fix-mbr-swap-removal: Avoid bailing-out early if not necessary

- eos-tech-support/eos-hack-reset-clubhouse
Here is the reset script, now with the logic moved to `hack-game-state-service`.
https://phabricator.endlessm.com/T24374
> eos-tech-support: add script to reset Clubhouse quests

- eos-tech-support/eos-fix-mbr-swap-removal
Before EOS 2.4.0 we shipped images with a different partition layout.
These are also vulnerable to the reclaim-swap corruption, so cover them
on this script as well.
https://phabricator.endlessm.com/T24454
> eos-fix-mbr-swap-removal: Add support for layouts prior to EOS 2.4.0

- eos-tech-support/eos-write-image
Both fallback and MokManager have been renamed upstream, so we need to
support the new paths while also staying backwards-compatible with the
older paths.
https://phabricator.endlessm.com/T25004
> eos-write-image: Add support for new ESP layout

- eos-tech-support/eos-convert-system
- eos-tech-support/eos-convert-system-qa
The eos-convert-system{,-qa} scripts have the same bug as described/seen in
https://phabricator.endlessm.com/T22687 which is that the journal dir
permissions are not correctly set after it is created, meaning that depending
on the execution environment of the script / setting of umask, some users (even
administrators) may be left unable to read the journal folder.
> tech-support/eos-convert-system*: fix journal dir perms

- debian/control
- eos-tech-support/eos-stage-flatpak
`flatpak-builder --install`, among other tools, creates remotes of the
form "org.vim.Vim-origin". `ostree config get KEY` splits KEY on the
first '.' it contains, leading to:
++ ostree --repo=/var/lib/flatpak/repo config get 'remote "org.vim.Vim-origin".url'
error: Key file does not have group “remote "org”
Since v2018.8, `ostree config get|set` accept a `--group` parameter,
precisely to deal with this case. Bump the version we depend on, and use
it.
https://phabricator.endlessm.com/T25253
> eos-stage-flatpak: cope with remote names containing '.'

- base-depends
Recently debian dropped the xz-utils priority from required to
standard[1], which means its no longer included by apt-bootstrap in the
OS. Although it's not required for the OS to operate, the ostree build
is currently breaking trying to create a xz compressed tarball. That
seems pretty useful generally, so make sure xz is included in the OS.
1. https://repo.or.cz/xz/debian.git/commit/3ed34568d0b311a6998a1aa8f6352b13849483ed
https://phabricator.endlessm.com/T25399
> base-depends: Add xz-utils to ensure xz available

- base-depends
The lame plugin that we carefully shipped in its own package is
now present in the regular gstreamer-plugins-good packages.
Remove this package that is being dropped from the distro.
https://phabricator.endlessm.com/T25185
> base-depends: lame plugin moved to gstreamer-plugins-good

- eos-core-depends
Add podman to the OS image, including slirp4netns and uidmap which are required
for using podman as an unprivileged user.
https://phabricator.endlessm.com/T25542
> core-depends: add podman and recommended packages

- eos-core-depends
The companion app itself is currently not available for download, and
we don't currently have the resources to resurrect it and investigate
issues that were reported before it was pulled from Google Play. (I have
the app installed on my tablet; while it can see my Endless computers on
the network, it fails to actually load any content from either of them.)
For the time being, remove the integration from the OS.
https://phabricator.endlessm.com/T25970
> Remove eos-companion-app-os-integration

- eos-tech-support/eos-stage-flatpak
Optionally takes the name of a remote to stage, instead of all of
them at once.
https://phabricator.endlessm.com/T26115
> eos-stage-flatpak: add a --remote-name option

- .gitignore
- debian/control
- debian/eos-tech-support.install
- debian/eos-tech-support.postinst
- debian/rules
- eos-dev-depends
- eos-dev-kernel-depends
- eos-dev-recommends
- eos-metapackage
- eos-tech-support-depends
- meson.build
- meson_options.txt
This would have prevented me from merging https://github.com/endlessm/eos-meta/pull/554 when fuse-overlayfs was not in the distro.
There are also some other fixes in here for things that lintian complained about. Many of them were harmless but one was real.
https://phabricator.endlessm.com/T26007
> Check that deps exist at build time

- eos-tech-support/eos-dev-unlock
It is useful in some situations (such as on a development system, or for
code that runs at boot) to install packages persistently on an
otherwise-unconverted system. `ostree admin unlock --hotfix` can be used
for this, but anecdotally can result in interesting behaviour if the
updaters are left running.
Support running `eos-dev-unlock --hotfix`, passing the argument through
to `ostree admin unlock`. The easiest way to achieve this is to just
pass all arguments (except `-h` or `--help`) through.
> eos-dev-unlock: pass args to ostree admin unlock

- eos-tech-support/eos-write-live-image
Previously eos-write-live-image only wrote the windows tool to the
removable drive if a non-writable live was requested.
This commit changes the behavior so that if a windows tool was
explicitly provided to the script, it will be written regardless
of whether the image was writable or not, and preserves the existing
behavior otherwise.
https://phabricator.endlessm.com/T26120
> eos-write-live-image: support windows tool for writable images

- eos-core-depends
It is recommended by gnome-settings-daemon and, because
we do not install recommended packaged by default, it
needs to be explicitly included.
https://phabricator.endlessm.com/T26202
> Add mousetweaks to eos-core-depends

- os-depends
We are dropping composite mode support. The CVBS connector is already
disabled on Endless Mini since 3.5.8.
https://phabricator.endlessm.com/T25621
> Remove eos-composite-mode

- eos-tech-support/eos-diagnostics
Due to a GJS update, the following warning was emitted many times:
```
(gjs:14968): Gjs-WARNING **: 19:41:56.918: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).
(Note that array.toString() may have been called implicitly.)
```
While fixing this I couldn't resist sneaking in another feature to get the Flatpak operation history out of the journal.
https://phabricator.endlessm.com/T26621
https://phabricator.endlessm.com/T26169
> eos-diagnostics: fix gjs warnings

- eos-core-depends
- eos-dev-suggests
- eos-toolbox-dev-depends
buildah was getting installed as a dep for the eos-toolbox-dev
metapackage in order to allow running toolbox inside eos-toolbox
containers.
Now that toolbox (0.0.10) doesn't depend on buildah anymore, lets
remove the dep as not needed anymore.
https://phabricator.endlessm.com/T26430
Signed-off-by: Andre Moreira Magalhaes <andre@endlessm.com>
> eos-toolbox-dev: Remove buildah

- eos-core-depends
- eos-toolbox-dev-depends
On balance, even if not 100% compatible, providing docker with podman improves
discoverability of the OS feature.
> eos-{core,toolbox-dev}-depends: add podman-docker

- debian/control
- eos-core-odroidu2-depends
- eos-core-rk3288-depends
- eos-core-sqwerty-depends
- odroidu2-depends
- os-odroidu2-depends
- os-rk3288-depends
- os-sqwerty-depends
- rk3288-depends
- sqwerty-depends
sqwerty was a Samsung-based device that never went beyond prototype.
odroidu2 was the prototype that predated that.
We haven't worked with these platforms in years.
RK3288 has been discontinued for EOS-3.7.0.
https://phabricator.endlessm.com/T26837
> Remove old ARM platforms

- eos-core-depends
The best all round solution for modern day CJK fonts is Noto,
a Google project.
Replace all the fonts we previously added for CJK support with Noto,
saving some disk space in the process.
https://phabricator.endlessm.com/T27024
> Switch to NotoCJK fonts for Chinese/Japanese/Korean

- eos-core-depends
speech-dispatcher needs at least one output module; without one, turning on the screen reader just plays a dummy message.  speech-dispatcher-espeak-ng is Recommended by the Debian package.  This adds 10.7 MB to the ostree: I think a functioning screen reader is a good way to spend this space.
sound-icons is also Recommended by speech-dispatcher which uses these sounds to signal events. It adds a mere 748 KB to the ostree. https://obs-master.endlessm-sf.com/request/show/20392 adds this package to our distro; this PR depends on that request.
https://phabricator.endlessm.com/T26227
> eos-core-depends: add recommends for speech-dispatcher

- eos-tech-support/eos-convert-system
We've updated our kernel location to match OSTree's suggested layout,
that means the kernel isn't where this script expected it to be anymore.
This isn't certain to work as intended if there are multiple kernel module
directories, so if a developer does a bunch of non-deterministic things
like eos-dev-unlock --hotfix and installing a new kernel before running
eos-convert-system, they may not end up booting the expected kernel.
https://phabricator.endlessm.com/T27124
> eos-convert-system: Find kernel and initramfs in new location

- eos-tech-support/eos-convert-system
Turns out grub won't notice these if they're not versioned.
Multiple installed versions isn't properly handled, as we never
deploy ostree in this way.
https://phabricator.endlessm.com/T27124
> eos-convert-system: Append kernel version to initramfs and vmlinuz

- eos-core-depends
This is the only colour emoji font in Debian, and is the colour emoji
font recommended by the ubuntu-desktop metapackage. We would be in good
company.
Depends on <https://obs-master.endlessm-sf.com/request/show/20413> to
import this package from Debian Buster.
https://phabricator.endlessm.com/T27027
> Add Noto Color Emoji font

- eos-tech-support/eos-enable-debian-apt
The easiest way to implement this is to treat an argument beginning with
'-' as being a request for help, since no Debian distros begin with 
hyphens.
This seems preferable to configuring a repo for the Debian distro
'--help', as I just did.
I also fixed a couple of warnings from shellcheck.
> eos-enable-debian-apt: support -h and --help

- eos-core-depends
Removes xapian-bridge from the list of dependencies of eos-core, so it
should no longer be included in the ostree. This will render all SDK1
apps nonfunctional, but we believe that there are no longer any in use,
and if there are we will port them.
https://phabricator.endlessm.com/T27277
> Remove xapian-bridge

- eos-core-depends
The gnome-software rebase brings with it some new packaging decisions
from upstream, including splitting the flatpak plugin out. We need to
install that plugin by default, and it’s marginally less maintenance
work to list it here than to add it as a hard-dependency of the
`gnome-software` package in our downstream packaging there.
https://phabricator.endlessm.com/T27325
> eos-core-depends: Add gnome-software-plugin-flatpak

- eos-initramfs-efi-depends
I broke the kernel build because plymouth isn't present when dracut
is invoked to make the efi initramfs+kernel blobs.
Adding eos-plymouth-themes here brings in several missing dependencies:
plymouth, plymouth-themes, eos-plymouth-theme-logos
> eos-initramfs-efi: Add eos-plymouth-theme

- eos-initramfs-efi-depends
Microcode utilities need to be present before running dracut so
early microcode updates can happen.  I've included:
amd64-microcode
intel-microcode
iucode-tool
Also, sort the list of dependencies.
> eos-initramfs-efi: Add microcode and utilities

- os-depends
This (partially) enables shared folder support when running Endless OS
as a guest in Boxes, the only VM tool available on Endless OS. It adds
just 48KB (since we already ship its dependencies) and is conditionally
enabled by a udev rule which detects support for SPICE's WebDAV channel
at boot time.
https://phabricator.endlessm.com/T27317
> os-depends: install spice-webdavd

- eos-core-amd64-depends
- eos-core-i386-depends
- eos-installer-meta-amd64-depends
- eos-installer-meta-i386-depends
- eos-installer-meta-nexthw-depends
- os-amd64-depends
- os-depends
- os-ec100-depends
- os-i386-depends
- os-nexthw-depends
- os-s905x-depends
End support for Bitland Jerry. So, move the xserver-xorg back to
original place.
This reverts commit eafc4b93ac0e24605d16b82cedc55dcf4a2d28f1.
https://phabricator.endlessm.com/T26837
> Revert "Introduce platfrom specific xserver-xorg-* dependency"

- debian/control
- eos-core-arm64-depends
- eos-dev-kernel-arm64-depends
- eos-installer-meta-arm64-depends
- os-depends
We're reviewing Raspberry Pi 3+ and newer R&D efforts using mainline
u-boot and mainline kernel.
https://phabricator.endlessm.com/T27446
> Add generic ARM64 metapackage

- os-depends
This is needed to have the NVIDIA proprietary driver working under
rootless X and Wayland.
https://phabricator.endlessm.com/T26790
> Install nvidia-modprobe

- eos-tech-support/eos-convert-system
We've moved the ostree binaries during ostree build so /boot can be
empty for PAYG images. This makes eos-convert-system put them back
where debian expects them to be.
https://phabricator.endlessm.com/T27041
> eos-convert-system: Put the EFI binaries back where they came from

- debian/control
- s905x-depends
We're reviving our Amlogic S905X R&D efforts using mainline
u-boot and mainline kernel.
We're still sticking to armhf as the base arch (as that's the only
arch we can support for the Mali GLESv2 driver), but need to include
arm64 packages for the kernel and bootloader.
eos-core-s905x is still a good name for the metapackage, because the
packages shipped are not limited to a single specific product based
around S905X.
However, the ostree builder will need to use a product-specific
devicetree, so will use per-device platform names. Since we're starting
with the libretech_cc platform, add an alias as eos-core-libretech_cc which
is what the ostree user will use.
> Rework S905X metapackage

- base-depends
- eos-core-depends
- os-depends
After review and test Raspberry Pi 3B+, we can disable the unused
packages on ARM64 platform.
https://phabricator.endlessm.com/T27446
> base-depends: eos-core-depends: os-depends: Disable unused packages on ARM64

- eos-initramfs-efi-depends
In order for eos-paygd to start in the initramfs, we need the dracut
modules in eos-payg.git and eos-payg-nonfree.git to be included in
the initramfs built for payg images. So this commit adds dependencies on
both those packages. We will also need to include the modules on the
dracut command line.
This should not be merged until after these PRs which create the dracut
modules:
- https://github.com/endlessm/eos-payg/pull/45
- https://github.com/endlessm/eos-payg-nonfree/pull/20
https://phabricator.endlessm.com/T27037
> eos-initramfs-efi: Add eos-payg{-nonfree} deps

- debian/control
- eos-initramfs-efi-depends
To fix the eos3.6-nexthw kernel build error "nothing provides eos-initramfs-efi", we need to have eos-initramfs-efi package.
> Fix eos3.6-nexthw kernel build

- os-depends
This will be used for PAYG images to create a unified kernel EFI image.
> os-depends: Add systemd-boot-signed

- eos-dev-depends
It's the tool that the Debian GNOME team uses, but it's
not a dependency of any other Debian tool.
https://phabricator.endlessm.com/T27741
> Add git-buildpackage to eos-dev-depends

- eos-core-depends
We need efitools to make authenticated efi variable updates for
managing secure boot keys (PK, KEK, db) on PAYG systems.
https://phabricator.endlessm.com/T27106
> eos-core-depends: Add efitools for PAYG secure boot key management

- eos-core-depends
Allows access to network and device (eg MTP) filesystems from
applications such as VLC and Shotwell that do not access the
filesystem via GVfs.
https://phabricator.endlessm.com/T26298
> Add gvfs-fuse to core depends

- eos-core-depends
Provide GNOME Disk Usage Analyzer as a stopgap until GNOME Usage
reaches better maturity.
https://phabricator.endlessm.com/T27873
> Add baobab to core depends

- eos-initramfs-efi-depends
- os-depends
Depends on https://github.com/endlessm/ostree/pull/159.
https://phabricator.endlessm.com/T27607
> Add ostree-boot to os-depends|eos-initramfs-efi

- eos-core-depends
This reverts commit 071a7844ab9305dd36b1a9764f6191dc744445f0. Per https://phabricator.endlessm.com/T26202#728635, mousetweaks is no longer used in GNOME 3.34: the functionality is built in.
https://phabricator.endlessm.com/T26202
> Revert "Add mousetweaks to eos-core-depends"

- eos-dev-depends
- eos-tech-support/eos-add-to-desktop
Spotted while checking whether I should include `.desktop` in an email subject :-)
> eos-add-to-desktop: fix dekstop typo in comment

- eos-core-depends
In the spirit of a5d94b4a (which added pip to the ostree), allow people
to create Python virtual environments on unconverted Endless OS systems.
This package (and its dependency, python3.7-venv, which actually
contains the code) adds 44 kB to the installed system.
https://phabricator.endlessm.com/T28826
> eos-core: install python3-venv

- eos-tech-support/eos-diagnostics
On my system, this looks like:
```
NAME       DISKSIZE  DATA COMPR ALGORITHM STREAMS ZERO-PAGES TOTAL MEM-LIMIT MEM-USED MIGRATED MOUNTPOINT
/dev/zram0      23G 51.8M  4.1M lzo-rle         8       7765  7.6M        0B   192.5M      30B [SWAP]
```
I think it may be helpful for interpreting the RAM and "swap" usage
figures from 'free -mh'.
> eos-diagnostics: include 'zramctl' output

- eos-core-depends
https://phabricator.endlessm.com/T28777
> eos-core-depends: Add gnome-shell-extension-appindicator

- eos-core-depends
The same functionality provided by this package is now integrated in
udev 244, so we can drop it.
https://phabricator.endlessm.com/T29320
> eos-core: Drop u2f-hidraw-policy

- eos-core-depends
This feature is being moved from GNOME Shell to an extension
shipped by default.
Notice that this depends on https://github.com/endlessm/eos-build/pull/1090 -- the package doesn't exist yet.
https://phabricator.endlessm.com/T28778
> Include the eos-watermark-extension package by default

- eos-core-depends
It isn’t a hard dependency of the libpipewire client library, so has to
be explicitly pulled into the distribution.
https://phabricator.endlessm.com/T22259
> Include the pipewire daemon in the default distribution

- eos-core-depends
This feature is being moved from GNOME Shell to an extension
shipped by default.
https://phabricator.endlessm.com/T28568
> Include the eos-hack-extension package by default

- eos-core-depends
https://phabricator.endlessm.com/T29459
> Include the parental controls UI in the default distribution

- eos-tech-support/eos-write-live-image
We now have a command line option to fill the eoslive partition with
a file for persistent storage space.
Currently this is not a fast operation - truncating the file to size
appears to be slow, yet not quite as slow as zero filling the space
would be.  It is hoped that this will be faster in the future with
a non-FUSE exfat driver.  In that case we can reconsider whether
this mode of operation should be default.
Untested on NTFS.
https://phabricator.endlessm.com/T14891
> eos-write-live-image: Allow provisioning of persistent storage space

- eos-core-depends
This is not ready to replace PulseAudio just yet, and it does not seem
to be compatible side-by-side with PulseAudio.
https://phabricator.endlessm.com/T22259
> core: Drop pipewire

- eos-tech-support/eos-enable-coredumps
Use a symlink for sysctl.d/99-coredump.conf instead of hard-coding
paramenters into a file, so we use the parameters from the current
systemd-coredump.
https://phabricator.endlessm.com/T29287
> eos-enable-coredumps: Use current parameters from systemd-coredump

- eos-core-arm64-depends
Add corresponding u-boot to make khadas VIM2 boot.
https://phabricator.endlessm.com/T30324
> Add Amlogic U-Boot dependency to arm64 OSTree

- eos-core-depends
Leave it commented as a painful reminder that it needs to be uncommented before 3.9.
https://phabricator.endlessm.com/T30172
> core: Temporarily disable eos-hack-extension

- eos-tech-support/eos-write-live-image
We now leave at least 16M of free space for log files to be written to the
USB stick, and only make persistent storage at all if more and a 1G is free.
https://phabricator.endlessm.com/T30534
> eos-write-live-image: Fix persistent storage space requirements

- eos-core-depends
Add eos-desktop-extension to the list of core-depends
packages.
https://phabricator.endlessm.com/T30540
> core: Add eos-desktop-extension

- eos-tech-support/eos-write-live-image
This allows the user to choose the size to allocate for persistent
storage, as long as it is more than 1GB and still leaves 16-32MB for
logs of the Endless OS Installer tool for Windows.
https://phabricator.endlessm.com/T30600
> eos-write-live-image: Add --persistent-storage-size option

- eos-tech-support/eos-write-live-image
When working with ISOs, eos-write-live-image can loopback-mount the ISO
and copy the compressed squashfs image, leaving more space on the target
device for extra data, persistent storage etc.
https://phabricator.endlessm.com/T30598
> eos-write-live-image: Use squashfs image from ISOs

- eos-core-depends
The current hack extension master is updated to work with the
gnome-shell 3.37.3 so it can be added safely to the list of deps.
> core: Enable eos-hack-extension again

- eos-tech-support/eos-write-live-image
The goal of this parameter was to allow a certain amount of disk space
to be left free for changes to the Kolibri homedir.  However this means
that you have to know what the free space on the partition will be
before you run the command that populates the partition.
Instead, accept a --free-space parameter, and use the maximum of this
value (if provided) and 17 MB as the free space. This allows the caller
to directly request what they want: persistent.img filling all but X of
the free space.
Also fix some linter warnings. Actually `shellcheck` can't parse the current code at all:
```
In eos-tech-support/eos-write-live-image line 541:
if [ "$PERSISTENT" ]; then
^-- SC1009: The mentioned syntax error was in this then clause.
In eos-tech-support/eos-write-live-image line 556:
if [ …
```
> eos-write-live-image: Invert --persistent-size

- eos-core-arm64-depends
Add corresponding u-boot to make PINEBOOK Pro boot.
https://phabricator.endlessm.com/T30613
> Add Rockchip U-Boot dependency to arm64 OSTree

- debian/eos-tech-support.install
- eos-tech-support/data/eos-link-feedback.desktop
This is used by both our help pages and the Shell panel user menu to point users to our community forum for feedback.
This currently (3.8) lives in the Shell but we decided to move it here so we don't have to rebase this patch on every Shell rebase.
https://phabricator.endlessm.com/T30172
> eos-tech-support: Add eos-link-feedback.desktop

- eos-core-depends
We are removing the exploration center extension on 3.9.
https://phabricator.endlessm.com/T30720
> core: Drop eos-exploration-center

- eos-core-depends
We are removing the speedwagon integration on 3.9.
https://phabricator.endlessm.com/T30293
> core: Drop eos-speedwagon

- eos-tech-support/eos-write-live-image
I ran `eos-write-live-image` on a huge VM the other day, and had to bash it a bit to make it work. All the changes seem OK so here they are.
https://phabricator.endlessm.com/T30765
> eos-write-live-image fixes for use on build server

- eos-dev-suggests
Our current version is very old and doesn't work with latest GNOME and is causing some build failures on jenkins PR jobs.
The package got renamed to gnome-tweaks and latest from debian is 3.34.0. Let's remove it for now to fix the jenkins PR jobs and we can re-add later if needed.
> eos-dev-suggests: Drop gnome-tweak-tool

- eos-dev-suggests
This is causing a build failure on jenkins PR jobs and the app is available on flathub so let's drop it here.
> eos-dev-suggests: Drop d-feet

- eos-core-depends
gvfs-bin has been removed in favour of libglib2.0-bin. The latter
contains different tools (the `gio` tool rather than `gvfs-copy` and
`gvfs-rename` etc.) but they are at least maintained.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
https://phabricator.endlessm.com/T30813
> eos-core-depends: Replace gvfs-bin with libglib2.0-bin

- eos-tech-support/eos-write-live-image
By default, mkfs.exfat picks the cluster size (allocation unit) based on
the disk size.  On large disks this is 128 KiB, wasting a lot of space on
Endless Key with many small files.  Force it to 8 sectors, ie 4096 bytes.
A crap program I wrote suggests that more than 5 GiB of space is lost by using a 128 KiB cluster size rather than 4 KiB on the Endless Key. There are something like 45,000 files less than 128 KiB on the disk and 20,000 less than 4 KiB so it might actually be true.
https://phabricator.endlessm.com/T30817
> eos-write-live-image: Reduce exFAT cluster size

- eos-tech-support/eos-write-live-image
When I tested a 4 KiB cluster size image, desktop search performance
seemed really bad, with both the EknServices search provider and the
Kolibri search provider causing the exFAT FUSE process to consume 100%
CPU for several minutes.
Compromise on 32 KiB which appears to work OK.
https://phabricator.endlessm.com/T30817
> eos-write-live-image: Force 32 KiB exFAT cluster size

- eos-core-depends
This is to be able to access Apple DMG packages, necessary to create the
Endless Key image with Apple software.
https://phabricator.endlessm.com/T30829
> core: Add libfsapfs-utils package

- eos-core-depends
This is needed for the GNOME screen sharing support.
https://phabricator.endlessm.com/T30882
> eos-core-depends: Add gnome-remote-desktop

- eos-tech-support/eos-write-metrics-collector-usb
Erase and reformat the plugged in USB storage device for offline
metrics data collecting.
> eos-write-metrics-collector-usb: script to create collector USB

- eos-core-depends
Previously, git was installed only as a dependency of flapjack, which we
removed in 3adf120525d0e538b98e1dca0b9bf4ca90046001.
I believe it is too useful to exclude. However, it does add 38 MB to
the ostree.
https://phabricator.endlessm.com/T30935
> eos-core: Install git

- eos-core-depends
We are no longer shipping "Get app" icons in the desktop and eos-install-app-helper is no longer used/needed.
https://phabricator.endlessm.com/T30820
> eos-core: Drop eos-install-app-helper

- eos-tech-support/eos-write-metrics-collector-usb
The `lsblk` command after partprobe will return empty PATH for the
target disk. Add a udevadm settle to make sure the OS already has
the partition table change.
https://phabricator.endlessm.com/T31175
> eos-write-metrics-collector-usb: Fix empty PATH after partprobe

- eos-tech-support/eos-diagnostics
For some issues, debugging is assisted by having a list of EFI variables
and their contents.
Additionally, let's dump the secure boot key and some rudimentary PAYG
information.
https://phabricator.endlessm.com/T31142
> eos-diagnostics: Add some more information to the output

- eos-core-depends
The alsa-lib's configuration files have been moved to alsa-ucm-conf and
alsa-topology-conf since commit 1f37ba2a2b1c ("ucm: remove configuration
files (moved to alsa-ucm-conf repository)") and cdc8aacbb57c ("topology:
remove configuration files (moved to alsa-topology-conf repository)").
So, we have to install them respectively.
https://phabricator.endlessm.com/T31176
> eos-core: Add alsa-topology-conf and alsa-ucm-conf

- eos-tech-support/eos-stage-flatpak
- eos-tech-support/eos-stage-ostree
With our shiny new Fastly CDN we can appropriately pass through HTTP
authentication to our origin server and don't need to access it
directly.
https://phabricator.endlessm.com/T31157
> eos-stage-*: Use CDN for dev repo URLs

- eos-tech-support/eos-convert-system-qa
- eos-tech-support/eos-stage-ostree
The OS dev repos are now available without authentication, so there's no
longer any need to supply a password to embed in the remote URL.
https://phabricator.endlessm.com/T31288
> eos-stage-ostree: Remove password requirement

- eos-tech-support/eos-convert-system-qa
- eos-tech-support/eos-stage-flatpak
- eos-tech-support/eos-stage-ostree
This fixes eos-stage-ostree to use our now public repos without credentials.
https://phabricator.endlessm.com/T31288
> Backport ostree repo URL changes

- eos-core-depends
- eos-dev-suggests
- eos-toolbox-dev-depends
This removes podman-docker which is not available on debian bullseye.
https://phabricator.endlessm.com/T31300
> Use podman from debian bullseye

- eos-core-depends
`podman` depends on `runc | crun` which gets `runc` installed automatically as a dependency.
The problem is `runc` requires cgroupsv1, which is disabled on latest master, while `crun` works fine with cgroupsv2.
We should ship both to:
- allow users to delete existing containers created with `runc` as the runtime (any container created pre-4.0)
- allow users to create new containers with cgroupsv1 disabled (and cgroupsv2 enabled), which only works with `crun`
Note users still won't be able to use containers created with `runc` but they should be able to at least remove them with `podman` cmdline.
https://phabricator.endlessm.com/T31300
> eos-core-depends: Ship both runc and crun OCI runtimes

- eos-core-depends
The new package is named podman-toolbox instead of toolbox.
https://phabricator.endlessm.com/T31300
> Use the new toolbox version (Go version)

- eos-core-amd64-depends
- eos-core-depends
Some printer drivers like printer-driver-cnijfilter,
printer-driver-cnijfilter2 and printer-driver-escp are only available on
amd64 architecture. So, move them from general dependency to amd64 only.
Otherwise, arm64 OSTree will build failed on the dependencies.
Fixes: 823f129b350d ("eos-core: Depend on extra printer drivers")
https://phabricator.endlessm.com/T31261
> eos-core: Move printer drivers dependencies

- eos-core-depends
All the documentation in this guide has hand-drawn illustrations and animations which do not apply to Endless OS.
Let's remove this package from the ostree which should also take care of removing the reference to it from the landing page of Yelp.
https://phabricator.endlessm.com/T31392
> eos-core-depends: Drop gnome-getting-started-docs

- eos-core-depends
We are going to direct users to cheese's flatpak from flathub.
Some apps still use libcheese, but those should depend directly on it if so.
https://phabricator.endlessm.com/T31429
> eos-core: Drop cheese

- eos-core-depends
We have long since stopped offering the codec key for purchase & download, and have decided to drop this from the OS since the need for non-free codecs is now (mostly) handled by Flatpak.
Depends on https://github.com/endlessm/eos-image-builder/pull/971 and https://github.com/endlessm/eos-ostree-builder/pull/162.
https://phabricator.endlessm.com/T31520
> eos-core: Drop eos-codecs-manager

- base-depends
We used to split highcontrast-icon-theme out of gnome-accessibility-themes to avoid a GTK2 dependency, but the latest package from bullseye (which we will be using) already dropped the GTK2 dependency.
https://phabricator.endlessm.com/T31428
> base-depends: Replace highcontrast-icon-theme with gnome-accessibility-themes

- eos-tech-support/eos-download-image
This was added to work around a CloudFront limitation: you cannot download more than 20 GiB in one go, nor can you even issue a HEAD request to find out the file size.
Fastly (and for that matter Bunny) does not have this limitation, so we can remove this artificial restriction.
(We could go further and remove all the logic that downloads files in 20 GiB chunks, but that code is harmless.)
This PR also trims out an old special-case that I am 99% sure is not used any more.
https://phabricator.endlessm.com/T23134
> eos-download-image: Don't require --size with --url

- eos-core-depends
The only other requirements for the image builder are python3 and gpg,
which are already included. I believe this should only add 87kB to the
OS as mmdebstrap dependencies are apt, python3 and perl, which are
already in the OS.
https://phabricator.endlessm.com/T31702
> eos-core: Add mmdebstrap for running eos-image-builder

- eos-core-depends
This tool is very useful for remote technical support. Having it
pre-installed in the OS simplifies the instructions we need to give to
the user who needs support.
https://phabricator.endlessm.com/T31863
> eos-core: Install tmate

- eos-core-depends
Follow Debian to strip all of the non-free hooks. Also do not ship hplip
at all, just the hpcups filters.
https://phabricator.endlessm.com/T31860
> eos-core: Replace hplip with printer-driver-hpcups

- eos-core-depends
* ipp-usb package for driverless USB printing
* sane-airscan package for for driverless scanning
https://phabricator.endlessm.com/T31861
> eos-core: Add ipp-usb & san-airscan for driverless printer & scanner

- eos-core-depends
This used to be pulled in as a (transitive) dependency of something
else. (I'm not actually sure what.)
I think it is reasonable to include at least one of 'curl' and 'wget'.
Since we have historically shipped 'wget', and I found recent posts on
the forum assuming it was present, let's keep it.
https://phabricator.endlessm.com/T31889
> Explicitly depend on wget

- eos-core-amd64-depends
EOS is going to use driverless printers, so remove them.
https://phabricator.endlessm.com/T31859
> eos-core-amd64: Drop printer-drivers-cnijfilter{2} & printers-driver-escp

- eos-core-depends
EOS is going to install Debian's printer packages directly. There is no
more EOS downstream maintained system-config-printer to provide the
system-config-printer-gnome.
Besides, the gnome-control-center already provide the "Printers" UI to
manage the printers. So, EOS only needs the system-config-printer-common
as the backend.
https://phabricator.endlessm.com/T31858
> eos-core: Replace system-config-printer-gnome with system-config-printer-common

- eos-core-depends
This app is not widely used on Endless OS. It is unmaintained upstream,
and there are more modern alternatives covering the same (or more)
functionality, such as Connections and Remmina, available on Flathub.
https://phabricator.endlessm.com/T31658
> Remove vinagre from eos-core

- eos-core-depends
This has been obsolete since we started shipping gnome-remote-desktop in
14c07884f0d0e4cc72b929fea536227552a20194.
https://phabricator.endlessm.com/T31990
> eos-core: remove vino

- os-depends
We are switching from ntp to the simpler systemd-timesyncd.
https://phabricator.endlessm.com/T16376
> os: Drop ntp

- eos-dev-suggests
Newer debian packaging for shim puts the unsigned components in the
shim-unsigned package, which is marked to replace shim. This fixes the
check-deps test.
> dev: Suggest shim-unsigned instead of shim

- eos-core-depends
- eos-dev-suggests
We're adopting debian's malcontent packaging, and that uses the
malcontent-gui package name to provide the `malcontent-control` program.
https://phabricator.endlessm.com/T30746
> core: Change malcontent-control dependency to malcontent-gui

- eos-tech-support/eos-download-image
Mazen's [seeing][1] partial downloads of images, followed by (of course) GPG verification failing. I'm not sure why; my hypothesis is that CloudFront is serving a short response because its connection to S3 drops.  This is supported by [Amazon's documentation][0]:
> **Dropped TCP Connections**
>
> If the TCP connection between CloudFront and your origin drops while your origin is returning an object to CloudFront, CloudFront behavior depends on whether your origin included a Content-Length header in the response:
>
> - Content-Length header – CloudFront returns the object to the viewer as it gets the object from your origin. However, if the value of the Content-Length header doesn't match the size of the object, CloudFront doesn't cache the object.
So add a check that each request …
> eos-download-image: attempt to handle truncated responses

- os-depends
Now that systemd-timesyncd acquired the same functionality from
fake-hwclock and that we are installing and enabling systemd-timesyncd
instead of ntpd, we can drop fake-hwclock and rely on systemd-timesyncd
to provide a monotonic clock.
https://phabricator.endlessm.com/T32428
> os-depends: Drop fake-hwclock

- base-depends
- debian/control
- eos-dev-kernel-armhf-depends
- os-depends
- os-ec100-depends
- os-s905x-depends
We don't support this architecture anymore after the EOS 3.8 series.
https://phabricator.endlessm.com/T30303
> Remove all references to armhf

- os-depends
GNOME has its own UI for configuring input methods. Try to remove the
duplicated im-config package.
https://phabricator.endlessm.com/T32538
> os-depends: Drop im-config

- eos-tech-support/eos-stage-ostree
Previously the development OS repo would not have reliable stable refs
because there might be multiple active branches publishing the stable
ref at the same time. For example, when `eos3.X` is branched but not yet
released, there are likely still builds for `eos3.X-1` happening and
both builds would be pushing to the `eos3a` stable branch ref. The same
goes for the new `latestN` branch ref.
Now the ostree builder configurations have been cleaned up so that only
one build at a time should be publishing a given stable or latest
branch. With that we can reliably use the same branch in any repo stage
and don't need to use heuristics to try to change it. `eos-stage-ostree`
is changed to simply update the repo URL and collection ID and leave the
branch alone. Anyone switching between OS refs is …
> eos-stage-ostree: Remove branch handling

- os-depends
This package is unnecessary and unused since we now have a kernel
version with native support for exFAT filesystems.
https://phabricator.endlessm.com/T32749
> Remove exfat-fuse from OS

- eos-core-depends
This module is a new companion to xdg-desktop-portal-gtk, maintained as
part of GNOME. It contains GNOME-specific interfaces that used to live
in -gtk prior to its 1.12 series.
The -gnome package depends on the other two so we only need to list this
one.
https://phabricator.endlessm.com/T32965
> eos-core: Depend on xdg-desktop-portal-gnome

- eos-core-depends
We take flatpak-builder directly from Debian, but maintain our own
Flatpak. Due to a security issue, flatpak-builder now has a versioned
dependency on a newer version of Flatpak than we have in the distro.
Remove flatpak-builder. We can readd it once we have updated Flatpak. In
the meantime the org.flatpak.Builder package from Flathub can be used
instead.
https://phabricator.endlessm.com/T32961
> Remove flatpak-builder

- eos-core-depends
gnome-user-guide is an empty transitional package which just depends on
gnome-user-docs.
https://phabricator.endlessm.com/T32935
> core: Update gnome-user-docs package name

- base-depends
Currently we ship the components of available locales via the `locales`
package and then compile them in the OSTree builder using `locale-gen`.
However, we compile all available locales so that the OS has the entire
set available. This takes about 20 minutes per OSTree build.
Instead, we can install the `locales-all` package, which has all the
locales pre-compiled into a package. At that point we no longer need the
`locales` package since there are no remaining locales to compile from
source components.
https://phabricator.endlessm.com/T32970
> base-depends: Switch from locales to locales-all

- eos-core-depends
The top-bar tweaks and dock which supersede this extension live in
eos-desktop-extension.
https://phabricator.endlessm.com/T33001
> core: Remove eos-panel-extension

- base-depends
- eos-core-depends
Since 3.26.0, gnome-orca has been a transitional package which just
depends on orca.
https://phabricator.endlessm.com/T32987
> core: install orca, not gnome-orca

- os-depends
(Draft because it require other packages in OBS)
Install pipewire for the core daemon; pipewire-audio-client-libraries
for enabling the audio modules in PipeWire; pipewire-pulse for
PulseAudio support; and libspa-0.2-bluetooth for bluetooth support.
https://phabricator.endlessm.com/T33042
> os-depends: Switch to PipeWire for audio

- base-depends
- os-depends
We need to install it at the same time libcanberra-pulse is
installed, otherwise it inadvertedly pulls the pulseaudio
into the image.
https://phabricator.endlessm.com/T33042
> Move PipeWire packages from os-depends to base-depends

- base-depends
This is a recommends of flatpak-builder. It is 2 MB.
(We already ship libzstd1.)
https://phabricator.endlessm.com/T33119
> Depend on zstd

- os-depends
Replace policykit-1 with polkitd-javascript, polkitd and pkexec to
migrate from old PKLA policies to JS rules.
https://phabricator.endlessm.com/T33151#927983
> os-depends: Install polkitd-javascript to migrate PKLA policies to JS rules

- os-depends
The commit ("UBUNTU: [Packaging] Downgrade firmware-sof-signed depends
to recommends") in linux-firmware makes firmware-sof-signed into
Recommends dependency, which leads EOS miss firmware-sof-signed, then
have no Intel SoF related firmware files.
This commit installs firmware-sof-signed again.
https://phabricator.endlessm.com/T33236#930671
> os-depends: Depend on firmware-sof-signed

- os-depends
Install nvidia-driver-libs to enable egl-wayland using nvidia feature.
https://phabricator.endlessm.com/T33217
> os-depends: Install nvidia-driver-libs to support wayland using nvidia

- os-depends
Install mesa-utils-extra to have eglinfo command for wayland session.
https://phabricator.endlessm.com/T33217
> os-depends: Install mesa-utils-extra for eglinfo command

- os-depends
Install libgles-nvidia2 for NVIDIA cards
https://phabricator.endlessm.com/T33217
> os-depends: Install libgles-nvidia2 for NVIDIA cards

- debian/endless-mimeapps.list
Previously, inserting a USB drive with an OSTree repo at its root would
cause Nautilus to prompt it to be opened with "Software Install". This
used to be correct, but when updating to GNOME Software 41 we dropped
our downstream support for USB updates.
This spiritually reverts 044c635e ("defaults: Associate GNOME Software
with ostree repos") and can be in turn reverted as and when Software
supports USB OS & app updates again.
https://phabricator.endlessm.com/T33546
> mimeapps: Dissociate ostree-repos from GNOME Software

- base-depends
In Debian's pipewire 0.3.54-1, the old pipewire-audio-client-libraries
package was split into pipewire-alsa and pipewire-jack.
https://salsa.debian.org/utopia-team/pipewire/-/commit/c17c45740d5efa5c8fec8acbfb359be33c73a52d
pipewire-alsa contains alsa plugins for pcm and ctl using pipewire. The
package (like pipewire-audio-client-libraries) drops a symlink into
/etc/alsa/conf.d pointing to
/usr/share/alsa/alsa.conf.d/50-pipewire.conf which causes these to be
used. (It also contains an example in /usr/share/doc/pipewire/examples
for how to make PipeWire the default ALSA output; we don't use this at
present.)
pipewire-jack contains alternative implementations of the JACK client
libraries, implemented in terms of Pipewire. These are not on the
library path by default (though there is an …
> base-depends: Depend on pipewire-alsa

- os-depends
Install libnvidia-allocator1 and libnvidia-egl-gbm1 for GBM with NVIDIA
devices.
https://phabricator.endlessm.com/T33820
> os-depends: Install more nvidia libs for GBM with NVIDIA device

- os-depends
Install switcheroo-control to let the user choose using integrated, or
the other GPU, if there are more than one GPU in the system.
https://phabricator.endlessm.com/T33814
> os-depends: Install switcheroo-control for dedicated Graphics cards

- os-depends
Debian's new systemd (since 251.2-3) places the EFI stub into systemd-boot-efi package which EOS uses for the PAYG platforms. So, for the new schema, EOS signs it as systemd-boot-efi-signed to be installed.
Besides, systemd-boot-efi-signed is the dependent package of EOS' systemd-boot. Therefore, install the systemd-boot for PAYG systems.
Fixes: 8721ff2214cf ("os-depends: Add systemd-boot-signed") https://phabricator.endlessm.com/T33862
> os-depends: Install systemd-boot

- debian/control
EOS 5+ tries to install the base-files without epoch in the version string which uses the same schema as Debian's base-files. Therfore, add the prevoius EOS base-files with epoch into the conflict list.
https://phabricator.endlessm.com/T33521
> Make base-files with epoch become conflict

- os-depends
Debian's new systemd (since 247.9-2) moves systemd-timesyncd from Depends to Recommends. But, EOS does not install the recommended dependent packages by default. To have the NTP, let's install systemd-timesyncd.
https://phabricator.endlessm.com/T33863
> os-depends: Install systemd-timesyncd

- eos-tech-support/eos-diagnostics
Add the RTC information for timing, especially for the PAYG feature.
We understand that the batt_status field may not be accurate, for example the mail on the internet: RTC batt_status always okay [1]. However, if "batt_status" shows "dead", then it must be something wrong. The field information might be improved by Linux kernel in the future.
[1]: https://lkml.iu.edu/hypermail/linux/kernel/1610.0/00094.html
https://phabricator.endlessm.com/T33898
> eos-diagnostics: Add RTC information

- debian/control
- os-depends
… in 2 different ways for 2 different reasons, described in each commit.
(Actually there is a third reason we might want this: files installed by checkbox contains many references to `pactl`.)
https://phabricator.endlessm.com/T34099
> Readd pulseaudio-utils to the OS

- eos-core-depends
Today I tried to use `adb` to do something on my Android phone, and it was made harder by the lack of appropriate udev rules to set permissions on the device.
Then I remembered a similar ticket I filed almost a year ago about Steam.
https://phabricator.endlessm.com/T33130
> Ship udev rules for Android devices & gaming controllers

- eos-core-depends
It has been noted that the first-run page that is displayed when you
first open a browser very strongly guides you to donate €35.  You might
reasonably (but wrongly) think this is Endless asking you for money.
This honor-ware page is also occasionally shown when the extension is
updated.
Stop autoinstalling AdBlock Plus. The 'eos-adblock-plus-extensions'
package just contains a tiny JSON file that instructs Chrome and
Chromium to install AdBlock Plus when it first launches. Existing users
will, I believe, keep the extension.
https://phabricator.endlessm.com/T34534
> Don't autoinstall AdBlock Plus

- eos-core-depends
This reverts commit 90ada88ed00e7a8ffc1fcefccbb3e4fcde1fdb6e.
This has the side-effect of removing /usr/share/chromium, which causes
Chromium to fail to start:
Apr 18 20:23:04 camille org.chromium.Chromium.flextop.chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Default.desktop[3649]: bwrap: Can't find source path /var/lib/flatpak/extension/org.chromium.Chromium.Extension.system-extensions/x86_64/1: No such file or directory
Back it out for now.
https://phabricator.endlessm.com/T34534
> Revert "Don't autoinstall AdBlock Plus"

- eos-tech-support/eos-write-installer
Probably not the most needed thing, but I needed to install `pv` on Silverblue. Making this message more useful for non-Debian-based OSes would be welcome here.
> eos-write-installer: Mention Silverblue

- os-depends
The gdm will need the scripts from nvidia-suspend-common to enable Wayland on the models equippied with NVIDIA card since gdm v43.x.
https://phabricator.endlessm.com/T34956
> os: Depend on nvidia-suspend-common

- meson.build
This test constructs a massive `apt-get install` line to check that the
metapackages are installable. It keeps hitting Meson's default 30-second
timeout in Jenkins.
Make the number bigger!
> Increase test timeout time

- base-depends
We do not ship VAAPI drivers in the OS.
Previously, we added symbolic links to pick up the drivers from a
Flatpak, if installed, but we are removing these because:
1. The drivers stopped working on the host for unknown reasons
2. Very little in the base OS uses GStreamer anyway
So there is no need to ship these libva-based GStreamer elements. They
never previously worked anyway, because we previously shipped a
systemwide GStreamer element cache which was precomputed on our build
server which did not have VAAPI drivers installed, and was not
recomputed if the VAAPI drivers were installed client-side.
https://phabricator.endlessm.com/T32994
https://phabricator.endlessm.com/T34998
> Remove gstreamer1.0-vaapi from OS

- eos-tech-support/eos-write-installer
Ran into this when using Silverblue; I needed to install `parted` to be able to use `partprobe`, otherwise it failed with:
```
eos-write-image: line 222: partprobe: command not found
```
> eos-write-installer: Add `partprobe` to dependencies

- eos-core-depends
GNOME upstream prefers anthy, but Debian and Ubuntu prefer mozc.
Debian's gnome-desktop package (which we use) is patched to prefer mozc.
No migration is provided for existing anthy users, who will need to
reconfigure their input method.
https://phabricator.endlessm.com/T35060
> Install ibus-mozc, not ibus-anthy, for Japanese input

- eos-tech-support/eos-write-installer
- eos-tech-support/eos-write-live-image
- os-depends
exfat-utils came from the FUSE implementation of exFAT and have been
removed from Bookworm.
exfatprogs are from the team that submitted & maintain the in-kernel
exFAT implementation.
https://phabricator.endlessm.com/T35035
> Replace exfat-utils with exfatprogs

- eos-core-depends
GNOME Shell 43 includes a built-in screenshot tool.
gnome-screenshot 41 is still present in Bookworm but installing it means that a desktop search for "screenshot" produces two confusingly-similar results.
https://phabricator.endlessm.com/T35034
> eos-core: Remove gnome-screenshot

- eos-core-depends
This extension is not compatible with gnome-shell 43, and we are no longer developing Hack.
https://phabricator.endlessm.com/T35054
> eos-core: Remove eos-hack-extension

- base-depends
EOS 5.1(+) includes many GTK 4 applications in the base OS. So, add ibus-gtk4 to support input methods.
https://phabricator.endlessm.com/T35149
> base-depends: Add ibus-gtk4

- eos-core-depends
- eos-toolbox-dev-depends
Add netavark & aardvark-dns for Podman 4.0(+)'s new network stack. [1]
[1]: https://www.redhat.com/sysadmin/podman-new-network-stack
https://phabricator.endlessm.com/T35149
> eos-core-depends: eos-toolbox-dev-depends: Add netavark & aardvark-dns

- debian/control
- debian/copyright
Spotted while investigating why we have three copies of WebKitGTK in the OS.
> Remove obsolete conflicts

- eos-tech-support/eos-write-installer
This branch adds more flexibility to eos-write-installer's command line arguments, so it is possible to run the command to add an OS image to a device which has already been formatted with eosinstaller. In addition, it adds a feature where, if the user doesn't specify a device, they are presented with a list of storage devices to choose from.
https://phabricator.endlessm.com/T35167
> eos-write-installer: Support running without --installer, or without a device path

- os-depends
The xprop utility, provided by x11-utils, is required by an Xwayland session script included in at-spi2-core.
https://phabricator.endlessm.com/T35173
> os-depends: Add x11-utils

- eos-tech-support/eos-diagnostics
eos-paygd writes extra logs to /var/log/eos-payg. These are useful on
systems where the journal is not persistent; and when we want deeper
history of PAYG state changes after the journal has been rotated.
I tested the following error cases:
- /var/log/eos-payg does not exist or is not readable; in this case the
section is omitted. This should not happen in practice – the
tmpfiles.d snippet sets mode 755.
- A file within is not readable; in this case the exception is included
in the diagnostic file.
- A file within contains invalid UTF-8; in this case the replacement
character is used.
If the directory is empty, the function returns empty string, which
means the section is omitted.
https://phabricator.endlessm.com/T33896
> eos-diagnostics: Collect extra PAYG logs

- eos-core-depends
This is very lightly used, not enough to justify updating it for GNOME
43 compatibility.
If we wish to bring this functionality back in future, we should instead
package https://pagure.io/background-logo-extension, which is actually
the ancestral source of the eos-watermark-extension code and which is
actively maintained by a core Shell developer for each Fedora release.
https://phabricator.endlessm.com/T35077
> Remove eos-watermark-extension from OS

- base-depends
- eos-tech-support/eos-diagnostics
gstreamer1.0-libav provides a gstreamer plugin that proxies to ffmpeg's codecs via its various libav* libraries. In theory that's nice since gstreamer applications can gain access to ffmpeg's codecs. In practice we were trimming down ffmpeg so much that it probably does not provide codecs for any media types that weren't already provided by native gstreamer plugins.
Furthermore, nothing we ship appears to have a hard dependency on the gstreamer elements provided by the libva plugin. We've also dropped the `/var/lib/codecs` system that provided the less patent encumbered ffmpeg extra libraries.
By extension, this also removes the ffmpeg libraries since gstreamer1.0-libav was the only thing we shipped using them. That simplifies our development by not having to analyze the legality of all …
> Remove gstreamer1.0-libav from OS

- base-depends
- eos-tech-support/eos-diagnostics
This reverts commit 73f27a845db9f92b2197f6430af4dd0621578322. It turns out that freerdp still uses ffmpeg and we don't want to go upending things at this stage in our development. As long as ffmpeg is going to be in the OS, we might as well make the components available to gstreamer applications.
https://phabricator.endlessm.com/T35225
> Revert "Remove gstreamer1.0-libav from OS"

- debian/endless-mimeapps.list
eos-launch.desktop has been removed, and the use of the endlessm-app: scheme with it.
https://phabricator.endlessm.com/T31635
> mimeapps: Remove endlessm-app: handler

- eos-core-depends
It provides `/usr/share/containers/storage.conf`, which contains sane storage settings that are different than the settings statically linked into podman. In particular, it sets the default driver to `overlay` rather than the builtin default of `vfs`.
https://phabricator.endlessm.com/T35229
> eos-core: Add containers-storage for podman

- base-depends
- eos-tech-support/eos-diagnostics
This reverts commit 9439f13f3b723f128fac99fde39a41ee25287c24. For real this time. The only other user of ffmpeg was freerdp, and it was actually useless since our ffmpeg doesn't have H.264 codecs. So, freerdp has been changed to not build against ffmpeg and now gstreamer1.0-libav is the last user of it. After this, EOS will be free of ffmpeg.
https://phabricator.endlessm.com/T35225
> Revert "Revert "Remove gstreamer1.0-libav from OS""

- eos-core-depends
/etc/cni/net.d/87-podman-bridge.conflist refers to several plugins from
this package; without it, attempting to run some configurations of
containers (such as via docker-compose) fails with errors like:
> ERROR: for postgres  preparing container
> 3e95923481bbf2f48645eff5da2c92e84b40f723f518153d270f703269fb3752 for
> attach: plugin type="bridge" failed (add): failed to find plugin
> "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni
> /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]
With this package installed, `docker-compose` can be used successfully
from a toolbox container against podman on the host.
It is 45 MiB which I feel a bit bad about, but maybe we can reclaim that
somewhere else in the OS.
> core: Add containernetworking-plugins

- os-depends
EOS has dropped EOS downstream pulseaudio with epoch version and use the pulseaudio related packages from Debian directly since EOS 6.0. However, the epoch version makes EOS' downstream pulseaudio newer than Debian's. It is okay for OSTree, because EOS build each OSTree commit from fresh installation. But, the version conflict will happen in container and eos-dev-unlock systems when do "apt upgrade". So, add the version constraint to pulseaudio-utils package to avoid the version conflict.
https://phabricator.endlessm.com/T35072
> os-depends: Avoid install old EOS downstream pulseaudio packages

- debian/eos-tech-support.install
- eos-tech-support/data/eos-link-feedback.desktop
eos-panel-extension used to have a menu item which invoked this (hidden) desktop file, which opens our forum in the web browser.
Since EOS 5 we have not used eos-panel-extension, so this desktop file is unused. Our forum is now available to “install” (as an Epiphany web app) from GNOME Software.
> Stop installing eos-link-feedback.desktop

- eos-tech-support/eos-write-installer
For 3 years eos-installer has supported installing images that do not have an `.asc` detached GPG signature, only a `.sha256` file containing a SHA256 digest of the image. This is to allow installing images built by third parties, who do not have access to our image signing key.
However, `eos-write-installer` has continued to insist on the `.asc` file being present.
Fix this; and fix a recently-introduced regression.
https://phabricator.endlessm.com/T35362
> eos-write-installer: Support images without .asc signature; fix finding image partition after repartitioning

- eos-tech-support/eos-download-image
I found this in my `git stash` for this repo, apparently from August 2021.
```diff
-/tmp/eos-eos5.1-amd64-amd64.240103-025438.base.img.xz (48%)
+/tmp/eos-eos5.1-amd64-amd64.240103-025438.base.img.xz (1.7 GB / 3.5 GB, 48%)
```
This does add a dependency on GLib and pygobject whereas currently this script uses mainly built-in Python modules plus the widely-available `requests`. It's not a problem on Endless OS but we do document how to run this script on other Linux systems (and possibly even macOS?). Maybe that is reason enough to reject this PR.
> eos-download-image: Add size to progress indicator

- debian/control
- eos-tech-support/eos-download-image
distutils.version is deprecated:
$ python3 -c 'import distutils.version; distutils.version.LooseVersion("1")'
<string>:1: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
> eos-download-image: Use packaging.version.Version

- eos-tech-support/eos-diagnostics
This partially reverts b6cb358cad2af72fd6e2bb29b5be9d4f692fd21d
(“eos-diagnostics: Add PipeWire information”).
On my system, this produces 10,221 lines of JSON. This is almost a
quarter of the full diagnostic file at 42,697 lines, of which 24,000
lines is the journal.
I for one have never found this output useful, and in fact it is really
annoying to have to scroll past to get down to the journal. It lists all
the pipewire modules we ship (redundant, we know what they are) and all
the interesting information about devices & clients is in the `pw-cli
info all` output.
> eos-diagnostics: Remove pw-dump output

- eos-core-depends
This is all that is needed to configure a Wireguard VPN from the CLI: we
already ship the kernel module.
This was requested on our forum
<https://community.endlessos.com/t/wireguard-support/22663>. While there
are workarounds for us not shipping this package, we may as well add it:
it is just a few hundred kilobytes.
https://phabricator.endlessm.com/T35393
> core: Add wireguard-tools to OS

- eos-tech-support/eos-dev-unlock
- eos-tech-support/eos-diagnostics
Since https://github.com/endlessm/eos-ostree-builder/commit/1bda62eeaecb4a34dbdd7eef78afebd879076054 we have completely wiped /var in the ostree:
> Anything in `/var` is wasted space in the commit since it will mounted over at runtime. OSTree's deploy code has been warning about this for years and it may eventually become a hard failure.
Adjust `eos-dev-unlock` to not try to populate /var/cache/debconf from the ostree deployment; and adjust `eos-diagnostics` to stop using the presence of `/var/cache/debconf` to detect that `eos-dev-unlock` has been run.
> Adapt scripts for lack of /var/cache/debconf

- base-depends
This allows accessing webcams through Pipewire, which is the way of the
future for applications to stop needing a --devices=all sandbox hole.
https://phabricator.endlessm.com/T35327
> Install pipewire's libcamera modules

- os-depends
This utility has many convenient features for interacting with secure boot UEFI variables. In addition to managing the MOK state from userspace, it can:
* Show the current SecureBoot state
* Set the UEFI variables to enable verbosity in shim and fallback
* Show and set the current SBAT policy
* Dump out all the standard SecureBoot databases (PK, KEK, DB, DBX) in standard PEM format.
On debian you get this automatically as a dependency of shim-signed, but we use a different package for our signed shim programs.
https://phabricator.endlessm.com/T34488
> os: Add mokutil on amd64 for secure boot management

- eos-tech-support/eos-write-installer
Prior to commit ce670ad61b169bcf403b641e0b55a3e3139efb36, this script
could only be run as root. That commit allowed it to run as a regular
user, wrapping commands that need root with sudo.
In my local usage I found that the script would reliably fail after
writing eosinstaller to disk and adding an eosimages partition.
update_eosimages_part would not find any partition with the 'eosimages'
label; so EOSIMAGES_PART would be the empty string; so mkfs.exfat would
not be run; and then the check below this block would fail:
/dev/sdb has no eosimages partition... aborting!
On closer inspection, while `udevadm settle` can be successfully run as
an unprivileged user, it actually does something slightly different
depending on whether it is run as root or not:
- If invoked as root, it first pings …
> eos-write-installer: Run udevadm settle as root
